### PR TITLE
update dozeu

### PR DESCRIPTION
**Pull request by mr-c**
Supports https://github.com/vgteam/vg/pull/2867

### CODE REVIEW

**Comment by adamnovak** [comment]
@jeizenga Didn't you say there was a reason we aren't up to date with the latest Dozeu?

**Comment by mr-c** [comment]
If vgteam forks dozeu then I can send a PR with the minimum changes for non-x86

**Comment by adamnovak** [comment]
Looks like that was https://github.com/vgteam/dozeu/pull/5

I just merged that; I think we now need a PR that changes vg's
submodule URL to point at vgteam/dozeu.

**Comment by jeizenga** [comment]
Superceded by https://github.com/vgteam/vg/pull/2871

**Pull request closed without merging**
