### PR TITLE
VG::edit speedup

### PR DESCRIPTION
**Pull request by jonassibbesen**
Changed VG::edit so that paths indexes are only rebuild after all paths have been added. This makes editing and adding paths using *vg mod -i* significantly faster.

### CODE REVIEW

**Comment by adamnovak** [comment]
Jenkins, OK to test.

Also, Jenkins, add to whitelist.

**Comment by jonassibbesen** [comment]
There might be some special case that I am not considering where rebuilding the indexes after each path have been added matters. However all the tests I have done so far using *vg mod -i* have given the same results before and after the change.

**Comment by ekg** [comment]
I think it is not necessary. How much faster does this make it for you?

**Comment by jonassibbesen** [comment]
There seem to have been an issue with GitHub's data storage system the past day resulting in my comment first getting copied and then deleted. So here it is again.

> I think it is not necessary. How much faster does this make it for you?
> […](#)

It is pretty significant. Adding 8021 single-end mapped RNA-seq reads as paths to a graph build from chr21 (no variants) using *vg mod -i* goes from taking ~30 minutes to ~11 seconds.

**Comment by adamnovak** [comment]
I think Erik was talking about *rebuilding the indexes after every path* not being necessary.

This is a pretty great speedup.

**Pull request merged**
