### PR TITLE
NGI0 - Updating licensing aspects according REUSE

### PR DESCRIPTION
**Pull request by lnceballosz**
Hello,

We have been working within the **NGI0** framework, helping projects with their licensing and copyright management. After a quick check on your repository,I would like to propose some updates regarding copyright and licensing information. [REUSE](https://reuse.software/) specifications intend to make licensing easier by setting one way to display all this legal information through comment headers on source files that can be human - and machine – readable.

The REUSE tool makes the process of applying licenses to files and compliance checking much easier. Check this screencast:

https://download.fsfe.org/videos/reuse/screencasts/reuse-tool.gif

Feel completely free to adopt these specifications by merging this pull request.

### REUSE Features:

- SPDX copyright and license comment headers for all relevant files only in the `src/` directory (as an example on how to proceed)

- LICENSES directory with all licenses used on the repository (Please be aware that I added the general license MIT and also the text of Boost Software License 1.0 since I noticed that one file licensed under this one)
**Note:** there is also a text of a license in the original file LICENSE that I renamed as NOTICE that I could not identify and I could not find the file that refers to the same one, so please check this issue)

- Licensing and copyright display of image files. Please be aware that I licensed one images on the directory `doc/figures `as an example of how to create a license file for an image file. However, I recommend you to check the copyright and license information and if you agree merge this commit and proceed and create the license files for the rest of the images)

###     Files missing copyright and licensing information:

I added the comment headers with copyright and license information to the files only in the` src/` directory. Please also double check if the personal information in the headers is correct and consistent.

I provided a more detailed license information to `README` file as well.

I renamed the original LICENSE file to NOTICE, as good practice. Also keep in mind that the licenses texts make part now of the LICENSES directory I have created. 

### No contribution policy:

We have noticed that your project does not have a contribution policy. Therefore, we strongly recommend you to implement one. To get further information about this please check our documentation: https://download.fsfe.org/NGI0/V2/FSFE%20-%204%20-%20Free%20Software%20Contribution%20Policy.pdf

### Further REUSE compliance

In case you find REUSE useful, we offer a [wide range of tools](https://reuse.software/dev/) to help you to continuously check and display compliance with the REUSE guidelines.

Hope that helps and thank you very much for the amazing job!

### CODE REVIEW

**Comment by adamnovak** [comment]
Hello @lnceballosz ! Thanks for doing all of this!

It would be nice to have the files connected to their licenses by little SPDX tags instead of just sort of explaining like we do in the current LICENSE.

I'm not sure to what extent it makes sense to mark all the files as copyright specifically by @ekg in specifically 2014; he wrote the whole codebase initially, but I think this PR would attribute to him files he hasn't actually touched, and which were written much later than 2014; can you @lnceballosz speak at all to how true REUSE thinks these copyright notices should be, or what to do with files where the true copyright is such a mishmash?

I think most of the files have copyright of some pieces held by Erik, some by UC regents, and some by miscellaneous outside contributors, all cross-licensed under the open source licenses we're using. Where we've had to put overall copyright notices in the past I think we've punted and said the copyright belongs to "contributors" or the not-actually-a-legal-entity "vgteam".

I've had a look at the "contribution policy" concept. In my mind we've been operating on the assumption that, for people not employed to work on the project, the Github pull request system and the way that putting the changes up publishes them alongside the license file were sufficient indicators that the person contributing actually intended to license their contribution to everyone. But perhaps having some more formal documentation of that notion would provide a benefit?

I'm not sure we specifically want Developer Certificates of Origin, which look to my untrained eye like they might produce more commit message fiddling than they will end up buying us in lawsuit defense. But the people really in charge here, from the UCSC side, are going to be the UCSC IP lawyers. I will have to ask them if they have opinions on whether and how we should formalize a contribution policy.

**Comment by lnceballosz** [comment]
Hi Adam, 

Thanks for your response. The goal of my PR is to serve as example of the implementation of REUSE in the concrete case of your project. The PR was not intended to provide accurate information on who the copyright holder is. The project must double check the information by their own. In case of several people worked on a single file, then all the names should be included on the headers. One line for each contributor.

As for the contribution policy. You do not need to prepare one neither incorporate a DCO. However, a few lines on how the project
accepts contribution is a very nice and inviting way to attract contribution to the project. It also provides clarity on how people can
submit their work to the project.

Hope this clarifies things for you.

Thank you again for the attention to my PR.

Best,
Lina

**Comment by adamnovak** [comment]
OK, I've been back and forth with the UCSC IP people a little bit, and they want us to make sure we have a copyright notice in here somewhere for UC Regents, which I'm not sure we do already.

I know it's how a lot of people do it, but I feel that asking every contributor to add their copyright notice to every file they touch is quickly going to become unwieldy, and moreover still won't necessarily be accurate enough to actually rely on in a legal context.

**Comment by adamnovak** [comment]
Since we haven't actually taken this yet, I am going to close this on the theory that we won't ever get around to it.

If we do decide we want SPDX headers, I think it might make the most sense to run the REUSE tools and maybe hook them into the Makefile.

**Pull request closed without merging**
