### PR TITLE
Fix multithreading in mpmap paired end mapping

### PR DESCRIPTION
**Pull request by jeizenga**
Another premature PR from https://github.com/vgteam/vg/pull/1145. Edits the parallel functions for FASTQ and GAM so that they have the option to switch from single threaded to multithreaded mode. Before the multithreading on mpmap paired end mapping wasn't working, so it ran in single threaded the entire run.

### CODE REVIEW

**Comment by jeizenga** [comment]
@glennhickey @adamnovak 
I'm not seeing any changes to the Travis script, but suddenly it's failing the Mac build? Tried restarting it already, but I don't think it's timing out. Looks to me like it has an out-of-date Ruby. How do we get an updated Ruby installed on the Travis potato?

**Comment by adamnovak** [comment]
I think this was caused by https://github.com/Homebrew/brew/pull/3240 and specifically https://github.com/Homebrew/brew/commit/bcca2a7c6b80a6450bd8261af987a8da260b6b89

Homebrew no longer supports the Ruby 2.0.0 that we have been running on Travis. When we run `brew update`, we get the latest Homebrew, which doesn't run on the system-installed Ruby anymore.

Homebrew tries to be nice and install its own copy of Ruby 2.3.3 as it updates itself, but (I think because of the `rvm use` command that it looks like Travis is running for us at the top of the build) Homebrew continues to run under the existing Ruby 2.0.0 when invoked, and fails to work.

**Comment by adamnovak** [comment]
Here's what looks like the corresponding Travis issue: https://github.com/travis-ci/travis-ci/issues/8552

**Comment by jeizenga** [comment]
Pretty sure both of these failures aren't real.

**Pull request merged**
