### PR TITLE
enable vg call on cyclic graphs

### PR DESCRIPTION
**Pull request by ekg**
This doesn't change anything about `vg call`'s `LegacyCaller` logic, but it does change the way that we determine reference positions to report. Previously, as noted in #2453, call would break if it saw a cyclic path. This change will always report the snarl at the first reference position. The snarl start is determined as the first, and the snarl end is found by path iteration in the graph. This could result in mistakes, but at least it won't blow up. I've included a test that verifies this works in a simple graph with a cyclic path.

This should probably only merge after @glennhickey's ok.

### CODE REVIEW

**Comment by ekg** [comment]
I think we need tests to make that work correctly. I thought that we would
get the node handle / step handle in the right orientation. This is in the
handle graph documentation at least.

**Comment by glennhickey** [comment]
I see.  I don't think `get_next_step` goes backward when the given handle is reversed, though.  From xg's implementation:
```
as_integers(next_step)[0] = as_integers(step_handle)[0];as_integers(next_step)[1] = as_integers(step_handle)[1] + 1;
``` 
If I'm understanding that, we'd need to manually toggle get_previous if the start step handle is reversed wrt the ref path.  Anyway +1 for a test.

**Comment by ekg** [comment]
Seems I was confused. Maybe we should clarify the semantics then. If we
take a step on a handle, should get next follow the directions implied by
the relative orientation between the handle and the path?

**Comment by jeizenga** [comment]
IMO it would be a pretty big headache to change those semantics now that we've handlified so much of the path-based code, but it would be relatively simple to add a generic wrapper function over `get_next_step`/`get_previous_step` that does what you're describing.

**Comment by ekg** [comment]
Ok. Then in the iteration I need to check that the path is oriented the
same as the handle or not and iterate along the path appropriately.

**Pull request merged**
