### PR TITLE
Move all xg-related methods into handle based algorithms

### PR DESCRIPTION
**Pull request by ekg**
As discussed on this week's call, I'll be pulling in all the changes I made in xg0 here, testing at each step that things are OK. When we don't have any more non-handle xg interfacing, it will be trivial to drop in the new xg.

### CODE REVIEW

**Comment by ekg** [comment]
There is still a *lot* to do:

```
erik@foldy [06:43:03 PM] [~/vg/src] [handleify]
-> % grep -R xg.hpp .
./region_expander.hpp:#include "xg.hpp"
./sampler.hpp:#include "xg.hpp"
./haplotype_extracter.cpp:#include "xg.hpp"
./filter.hpp:#include "xg.hpp"
./chunker.hpp:#include "xg.hpp"
./haplotypes.hpp:#include "xg.hpp"
./path_index.hpp:#include "xg.hpp"
./readfilter.hpp:#include "xg.hpp"
./subcommand/convert_main.cpp:#include "../xg.hpp"
./subcommand/xg_main.cpp:#include "../xg.hpp"
./subcommand/benchmark_main.cpp:#include "../xg.hpp"
./subcommand/paths_main.cpp:#include "../xg.hpp"
./subcommand/gbwt_main.cpp:#include "../xg.hpp"
./subcommand/dotplot_main.cpp:#include "../xg.hpp"
./alignment.hpp:#include "xg.hpp"
./io/register_loader_saver_xg.cpp:#include "register_loader_saver_xg.hpp"
./io/register_loader_saver_xg.cpp:#include "../xg.hpp"
./io/register_libvg_io.cpp:#include "register_loader_saver_xg.hpp"
./io/register_loader_saver_xg.hpp: * \file register_loader_saver_xg.hpp
./gbwt_helper.hpp:#include "xg.hpp"
./xg.cpp:#include "xg.hpp"
./phase_unfolder.hpp:#include "xg.hpp"
./vectorizer.hpp:#include "xg.hpp"
./unittest/flow_sort_test.cpp:#include "../xg.hpp"
./unittest/gfa.cpp:#include "../xg.hpp"
./unittest/vpkg.cpp:#include "../xg.hpp"
./unittest/path_component_index.cpp:#include "xg.hpp"
./unittest/handle.cpp:#include "../xg.hpp"
./unittest/xg.cpp:#include "xg.hpp"
./unittest/cluster.cpp:#include "xg.hpp"
./unittest/convert_handle.cpp:#include "../xg.hpp"
./vg_set.hpp:#include "xg.hpp"
./surjector.hpp:#include "xg.hpp"
./haplotype_extracter.hpp:#include "xg.hpp"
```

**Comment by ekg** [comment]
@glennhickey I'm moving every reference to XG to PathPositionHandleGraph.

**Comment by ekg** [comment]
The tests may pass for 637c9c1. This is getting close to something we can merge back into master.

I believe that the hardest part of the job is done. I now have 700kb of patch against master, with ~10k lines added or subtracted. The mapper is fully free of any reference to xg. It just talks about a PathPositionHandleGraph which it occasionally casts to a VectorizableHandleGraph.

@adamnovak @glennhickey @jeizenga @jonassibbesen here's what's standing in the way of introducing the new xg:

```
-> % grep xg.hpp *hpp
alignment.hpp:#include "xg.hpp"
chunker.hpp:#include "xg.hpp"
filter.hpp:#include "xg.hpp"
gbwt_helper.hpp:#include "xg.hpp"
haplotype_extracter.hpp:#include "xg.hpp"
haplotypes.hpp:#include "xg.hpp"
path_index.hpp:#include "xg.hpp"
phase_unfolder.hpp:#include "xg.hpp"
readfilter.hpp:#include "xg.hpp"
region_expander.hpp:#include "xg.hpp"
sampler.hpp:#include "xg.hpp"
surjector.hpp:#include "xg.hpp"
vectorizer.hpp:#include "xg.hpp"
vg_set.hpp:#include "xg.hpp"
```

Many of these are still using pieces of the old xg interface.

We can also see who is using the XG class:

```
-> % grep -R XG * | cut -f 1 -d: | sort | uniq -c
      7 alignment.cpp
      7 alignment.hpp
      1 chunker.cpp
      2 chunker.hpp
      2 cluster.hpp
      1 deconstructor.hpp
      4 filter.cpp
      2 filter.hpp
      1 gbwt_helper.cpp
      5 gbwt_helper.hpp
      1 genotypekit.cpp
      1 genotypekit.hpp
     21 haplotype_extracter.cpp
     12 haplotype_extracter.hpp
     19 haplotypes.cpp
     25 haplotypes.hpp
      3 homogenizer.cpp
      2 homogenizer.hpp
      1 identity_overlay.hpp
      1 indexed_vg.hpp
      1 io/register_loader_saver_distance_index.cpp
      6 io/register_loader_saver_xg.cpp
      3 io/register_loader_saver_xg.hpp
      2 minimizer_mapper.cpp
      3 minimizer_mapper.hpp
      2 multipath_mapper.cpp
      1 multipath_mapper.hpp
      3 path_index.cpp
      3 path_index.hpp
      1 path_subgraph.hpp
      9 phase_unfolder.cpp
     10 phase_unfolder.hpp
      1 proto_handle_graph.hpp
      5 readfilter.cpp
      6 readfilter.hpp
      2 region_expander.cpp
      2 region_expander.hpp
      1 reverse_graph.hpp
      1 split_strand_graph.hpp
      1 srpe.hpp
      1 stream_index.hpp
      4 subcommand/annotate_main.cpp
      3 subcommand/benchmark_main.cpp
      1 subcommand/call_main.cpp
      2 subcommand/chunk_main.cpp
      3 subcommand/cluster_main.cpp
      4 subcommand/convert_main.cpp
      3 subcommand/dotplot_main.cpp
      4 subcommand/filter_main.cpp
      5 subcommand/find_main.cpp
      5 subcommand/gaffe_main.cpp
      4 subcommand/gbwt_main.cpp
     18 subcommand/index_main.cpp
      3 subcommand/inject_main.cpp
      1 subcommand/locify_main.cpp
      4 subcommand/map_main.cpp
      5 subcommand/minimizer_main.cpp
      6 subcommand/mpmap_main.cpp
      2 subcommand/msga_main.cpp
      3 subcommand/pack_main.cpp
      9 subcommand/paths_main.cpp
      4 subcommand/prune_main.cpp
      1 subcommand/sift_main.cpp
      2 subcommand/sim_main.cpp
      3 subcommand/srpe_main.cpp
      5 subcommand/surject_main.cpp
      2 subcommand/trace_main.cpp
      1 subcommand/validate_main.cpp
      3 subcommand/vectorize_main.cpp
      3 subcommand/viz_main.cpp
      9 subcommand/xg_main.cpp
      4 surjector.cpp
      2 surjector.hpp
      2 unittest/chunker.cpp
      1 unittest/cluster.cpp
     15 unittest/convert_handle.cpp
      8 unittest/gapless_extender.cpp
     10 unittest/gbwt_helper.cpp
      6 unittest/handle.cpp
     21 unittest/haplotypes.cpp
      3 unittest/mapper.cpp
      1 unittest/min_distance.cpp
      3 unittest/multipath_mapper.cpp
      1 unittest/path_component_index.cpp
     17 unittest/phase_unfolder.cpp
      2 unittest/readfilter.cpp
      4 unittest/sampler.cpp
     22 unittest/vg_algorithms.cpp
      5 unittest/vpkg.cpp
      7 unittest/xg.cpp
      2 variant_adder.cpp
      1 variant_recall.cpp
      1 vectorizer.cpp
      2 vectorizer.hpp
      6 vg_set.cpp
      3 vg_set.hpp
    203 xg.cpp
     38 xg.hpp
```

I believe that these pieces are more independent than the mapper was, and so should involve smaller and more self-contained changes.

Can we find a way to divide up this work by who knows the most about each piece?

The basic requirement is to replace all mentions of XG with a PathPositionHandleGraph or VectorizableHandleGraph. I'm typically using dynamic casts to get access to the methods added by VectorizableHandleGraph.

Once this is done, we can swap out the entire xg index in a much smaller move. Getting this change made is important for building graphs with many embedded paths. This will be key for working on top of large graphs from seqwish and for RNA seq alignment. We can't do either at scale now with vg.

**Comment by ekg** [comment]
I want to further clarify that the goal here is to move us into a place where independent tools convert GFA into various xgs that vg can work on top of. Loading an xg-style index is much faster than loading from .vg files.

I would also like vg to be able to go directly from GFA to xg without the vg intermediate step. There is a semantic mismatch between the serialization model of vg (chunked subgraphs with the path fragments overlapping them) and that of GFA and xg (whole graph).

An aside: @adamnovak I still think we should not be gzipping these files unless requested by the user.

**Comment by ekg** [comment]
Nope, CI is still broken. Ouch.

**Comment by adamnovak** [comment]
@ekg Since we actually have the XG as a concrete implementation, and since the casting means we have code that requires it, would it make sense to define a VectorizeablePathPositionHandleGraph to cover the combined interface? That seems to be what we would do given the rules we set out about having only the actually used nodes in our combinatorially-exploding inheritance graph.

**Comment by adamnovak** [comment]
I'll see about turning off gzip compression. With a little more framing or some kind of magic number, I think I can still let us load both tagged, concatenateable files and bare custom-format files, with the downside being that you can't concatenate compressed and uncompressed things together.

**Comment by ekg** [comment]
How do I determine what is causing these failures? The CI framework is like an onion.

**Comment by adamnovak** [comment]
Yiu mentioned you tracked stuff down already, but for future reference, it can help to go to the CI full report linked form the comments, and then the stdout/stderr logs for failing tests. Those in trun are Toil logs, and they may have messages about jobs leaving their own logs "indicating failure", and the job's log will follow. That in turn might have information about a failed Docker command, vg program crash, or problem with the toil-vg workflow itself.

**Pull request merged**
