### PR TITLE
Resolve a few problems that @mlin ran into in human testing

### PR DESCRIPTION
**Pull request by ekg**
We've been working through anecdotes featuring strange alignments.

The changes here should resolve most of what @mlin has run into these past few days.

### CODE REVIEW

**Comment by mlin** [comment]
@ekg cool -- the example I found with mapQ=0 but no reported secondary mapping, is the explanation that the mapQ had been penalized by overlap?

**Comment by ekg** [comment]
It was a mathematical error. I was taking the log of 0 for cases with
perfect uniqueness. This yielded an MQ of 0 in this case. I just got rid of
the whole idea of uniqueness in the MQ calculation and it seems to actually
have helped the yeast tests. I haven't been able to do a human sim test
today because our systems are not working. Let me know if this PR fixes
other examples you've found.

**Comment by ekg** [comment]
@glennhickey when trying to view the jenkins report I get this (after logging in)

image

**Comment by ekg** [comment]
Here are the results in the 1M sim. Seems fine.

# yeast

[yeast_sim.1M-f443b47.roc.pdf](https://github.com/vgteam/vg/files/961418/yeast_sim.1M-f443b47.roc.pdf)

# human

[human_sim.1M-f443b47.roc.pdf](https://github.com/vgteam/vg/files/961417/human_sim.1M-f443b47.roc.pdf)

The human results feature an error, which is that we were ignoring the mtDNA and dummy sequences that bwa mem is using.

**Comment by glennhickey** [comment]
thanks for letting me know.  vgteam's supposed to be whitelisted but I'm
not surprised that didn't work on the first try.  will try to get it sorted
out (but the entire server seems down atm).

**Pull request merged**
