### PR TITLE
Get MCMC genotyper working on small test case 

### PR DESCRIPTION
**Pull request by code-s-witch**
This PR replaces #2778.

### CODE REVIEW

**Comment by code-s-witch** [comment]
@jeizenga  i removed all .vscode files, unwanted scripts

**Comment by adamnovak** [comment]
Actually I bet the problem is here, where you start sending output to cerr instead of cout in `call_main.cpp`: https://github.com/vgteam/vg/pull/2796/files#diff-287f1772c263b26289289d3a81910cbeL434-R434

Can you put it back? It might start working then.

**Comment by code-s-witch** [comment]
Ok, i undid the change and pushed.

**Comment by adamnovak** [comment]
@code-s-witch Great!

But now it looks like someone (@jeizenga?) changed the type of multipath alignments from `MultipathAlignment` to `multipath_alignment_t`, which created a bunch of conflicts with changes you made on the same lines. Can you merge master into your branch again and resolve those?

Gitlab CI is failing because [Quay.io is broken today](https://status.quay.io/), which it uses to shuttle its builds around. We might just have to wait for it to get fixed before rerunning the tests.

**Comment by code-s-witch** [comment]
Adam, I resolved the merge conflicts and pushed changes.

**Comment by adamnovak** [comment]
Looks like the unit tests are doing something bad on Mac. We may want to grab someone with a Mac (me?) to be able to debug it.

**Comment by code-s-witch** [comment]
Okay, I integrated Jordan's new feature but two of the unit tests are
failing so I am working on fixing them.

**Comment by adamnovak** [comment]
Almost all of this is in master now. We're going to make a new one for integration of the new scoring function and the min cut algorithm.

**Pull request closed without merging**
