### PR TITLE
Mapperific

### PR DESCRIPTION
**Pull request by ekg**

### CODE REVIEW

**Comment by ekg** [comment]
@jeizenga build this branch, then run the following test:

Make the test graph:

```
echo '{"edge": [{"to": 64596, "from": 64594}, {"to": 64596, "from": 64595}, {"to": 64594, "from": 64593}, {"to": 64595, "from": 64593}, {"to": 64593, "from": 64591}, {"to": 64593, "from": 64592}, {"to": 64591, "from": 64590}, {"to": 64592, "from": 64590}, {"to": 64590, "from": 64588}, {"to": 64590, "from": 64589}, {"to": 64588, "from": 64587}, {"to": 64589, "from": 64587}, {"to": 64587, "from": 64585}, {"to": 64587, "from": 64586}, {"to": 64585, "from": 64583}, {"to": 64585, "from": 64584}, {"to": 64586, "from": 64583}, {"to": 64586, "from": 64584}, {"to": 64583, "from": 64581}, {"to": 64583, "from": 64582}, {"to": 64584, "from": 64581}, {"to": 64584, "from": 64582}, {"to": 64581, "from": 64579}, {"to": 64581, "from": 64580}, {"to": 64582, "from": 64579}, {"to": 64582, "from": 64580}, {"to": 64579, "from": 64578}, {"to": 64580, "from": 64578}, {"to": 64578, "from": 64576}, {"to": 64578, "from": 64577}, {"to": 64576, "from": 64575}, {"to": 64577, "from": 64575}, {"to": 64575, "from": 64574}, {"to": 64574, "from": 64573}, {"to": 64573, "from": 64572}, {"to": 64572, "from": 64570}, {"to": 64572, "from": 64571}, {"to": 64570, "from": 64569}, {"to": 64571, "from": 64569}, {"to": 64569, "from": 64567}, {"to": 64569, "from": 64568}, {"to": 64567, "from": 64566}, {"to": 64568, "from": 64566}, {"to": 64566, "from": 64564}, {"to": 64566, "from": 64565}, {"to": 64564, "from": 64563}, {"to": 64565, "from": 64563}, {"to": 64563, "from": 64561}, {"to": 64563, "from": 64562}, {"to": 64561, "from": 64560}, {"to": 64562, "from": 64560}, {"to": 64560, "from": 64558}, {"to": 64560, "from": 64559}, {"to": 64558, "from": 64557}, {"to": 64559, "from": 64557}, {"to": 64557, "from": 64555}, {"to": 64557, "from": 64556}, {"to": 64555, "from": 64553}, {"to": 64555, "from": 64554}, {"to": 64556, "from": 64553}, {"to": 64556, "from": 64554}, {"to": 64553, "from": 64552}, {"to": 64554, "from": 64552}, {"to": 64552, "from": 64550}, {"to": 64552, "from": 64551}, {"to": 64550, "from": 64549}, {"to": 64551, "from": 64549}, {"to": 64549, "from": 64547}, {"to": 64549, "from": 64548}, {"to": 64547, "from": 64546}, {"to": 64548, "from": 64546}], "node": [{"id": 64596, "sequence": "CGCCT"}, {"id": 64594, "sequence": "G"}, {"id": 64595, "sequence": "T"}, {"id": 64593, "sequence": "GG"}, {"id": 64591, "sequence": "C"}, {"id": 64592, "sequence": "T"}, {"id": 64590, "sequence": "G"}, {"id": 64588, "sequence": "G"}, {"id": 64589, "sequence": "A"}, {"id": 64587, "sequence": "GT"}, {"id": 64585, "sequence": "G"}, {"id": 64586, "sequence": "A"}, {"id": 64583, "sequence": "T"}, {"id": 64584, "sequence": "C"}, {"id": 64581, "sequence": "G"}, {"id": 64582, "sequence": "A"}, {"id": 64579, "sequence": "C"}, {"id": 64580, "sequence": "T"}, {"id": 64578, "sequence": "CGGG"}, {"id": 64576, "sequence": "T"}, {"id": 64577, "sequence": "C"}, {"id": 64575, "sequence": "G"}, {"id": 64574, "sequence": "ATCTCTACTAAAAATACAAAAAATTA"}, {"id": 64573, "sequence": "CATCCTGGCTAACACGGTGAAACCCC"}, {"id": 64572, "sequence": "GGATCACGAGGTCAGGAGATCGAGAC"}, {"id": 64570, "sequence": "C"}, {"id": 64571, "sequence": "T"}, {"id": 64569, "sequence": "GGG"}, {"id": 64567, "sequence": "C"}, {"id": 64568, "sequence": "T"}, {"id": 64566, "sequence": "GAGG"}, {"id": 64564, "sequence": "T"}, {"id": 64565, "sequence": "C"}, {"id": 64563, "sequence": "CAGCACTTTGGGAGGC"}, {"id": 64561, "sequence": "C"}, {"id": 64562, "sequence": "T"}, {"id": 64560, "sequence": "CCTGTAATC"}, {"id": 64558, "sequence": "G"}, {"id": 64559, "sequence": "A"}, {"id": 64557, "sequence": "GGTGGCTCAC"}, {"id": 64555, "sequence": "C"}, {"id": 64556, "sequence": "T"}, {"id": 64553, "sequence": "G"}, {"id": 64554, "sequence": "T"}, {"id": 64552, "sequence": "GCCAGGC"}, {"id": 64550, "sequence": "C"}, {"id": 64551, "sequence": "T"}, {"id": 64549, "sequence": "TA"}, {"id": 64547, "sequence": "G"}, {"id": 64548, "sequence": "A"}, {"id": 64546, "sequence": "CCTCTTTGCTCCTTAAATATATATTTAT"}]}' | vg view -Jv - >fail_full_length_bonus.vg
```

Try to run a right-pinned alignment with a full length bonus of 5.

```
-> % vg align -s $(cat fail_full_length_bonus.seq.txt) -T 5 -p -j -D fail_full_length_bonus.vg 
error:[gssw] Stuck in main matrix!
vg: src/gssw.c:1871: gssw_alignment_trace_back_byte: Assertion `0' failed.
[1]    3616 abort (core dumped)  vg align -s $(cat fail_full_length_bonus.seq.txt) -T 5 -p -j -D 
```

:boom:

**Comment by ekg** [comment]
@jeizenga hit another problem. The pattern is that the traceback is tacking on an additional base to the alignment sequence. To reproduce:

```
echo -n '{"node": [{"id": 83950, "sequence": "CTTGTCTAGAATACTACAGAT"}, {"id": 83948, "sequence": "C"}, {"id": 83949, "sequence": "T"}, {"id": 83947, "sequence": "TACCCATCCAAGTCTTTGCT"}, {"id": 83946, "sequence": "TCTGCAGTGCCAAGGGGATA"}, {"id": 83944, "sequence": "G"}, {"id": 83945, "sequence": "A"}, {"id": 83943, "sequence": "CTAGAGA"}, {"id": 83941, "sequence": "G"}, {"id": 83942, "sequence": "A"}, {"id": 83940, "sequence": "TCCCCACAG"}, {"id": 83938, "sequence": "A"}, {"id": 83939, "sequence": "T"}, {"id": 83937, "sequence": "C"}, {"id": 83935, "sequence": "A"}, {"id": 83936, "sequence": "T"}, {"id": 83934, "sequence": "GT"}, {"id": 83932, "sequence": "C"}, {"id": 83933, "sequence": "T"}, {"id": 83931, "sequence": "TGGCCAGCCTCCAGCTG"}, {"id": 83929, "sequence": "C"}, {"id": 83930, "sequence": "A"}, {"id": 83928, "sequence": "C"}, {"id": 83926, "sequence": "C"}, {"id": 83927, "sequence": "T"}, {"id": 83925, "sequence": "CTTGGACCCAGGCAAGCGGGGCTCTG"}, {"id": 83924, "sequence": "ACCTAGCACAGGCTGACCAGCCCATC"}, {"id": 83923, "sequence": "GCTTCATCTACTCATGTACCTGCAGC"}, {"id": 83922, "sequence": "GAGTAGGAGAAGCAGGGGTGGTATCT"}, {"id": 83920, "sequence": "T"}, {"id": 83921, "sequence": "G"}, {"id": 83919, "sequence": "GATGTGTCTTCACCTT"}, {"id": 83917, "sequence": "G"}, {"id": 83918, "sequence": "T"}, {"id": 83916, "sequence": "AGACTGAGGCCCTGACTTCAG"}, {"id": 83915, "sequence": "CTCATCTTATAGATAGGGCTA"}, {"id": 83913, "sequence": "C"}, {"id": 83914, "sequence": "A"}, {"id": 83912, "sequence": "TCAGGTAAGC"}, {"id": 83910, "sequence": "A"}, {"id": 83911, "sequence": "G"}], "edge": [{"from": 83948, "to": 83950}, {"from": 83949, "to": 83950}, {"from": 83947, "to": 83948}, {"from": 83947, "to": 83949}, {"from": 83946, "to": 83947}, {"from": 83944, "to": 83946}, {"from": 83945, "to": 83946}, {"from": 83943, "to": 83944}, {"from": 83943, "to": 83945}, {"from": 83941, "to": 83943}, {"from": 83942, "to": 83943}, {"from": 83940, "to": 83941}, {"from": 83940, "to": 83942}, {"from": 83938, "to": 83940}, {"from": 83939, "to": 83940}, {"from": 83937, "to": 83938}, {"from": 83937, "to": 83939}, {"from": 83935, "to": 83937}, {"from": 83936, "to": 83937}, {"from": 83934, "to": 83935}, {"from": 83934, "to": 83936}, {"from": 83932, "to": 83934}, {"from": 83933, "to": 83934}, {"from": 83931, "to": 83932}, {"from": 83931, "to": 83933}, {"from": 83929, "to": 83931}, {"from": 83930, "to": 83931}, {"from": 83928, "to": 83929}, {"from": 83928, "to": 83930}, {"from": 83926, "to": 83928}, {"from": 83927, "to": 83928}, {"from": 83925, "to": 83926}, {"from": 83925, "to": 83927}, {"from": 83924, "to": 83925}, {"from": 83923, "to": 83924}, {"from": 83922, "to": 83923}, {"from": 83920, "to": 83922}, {"from": 83921, "to": 83922}, {"from": 83919, "to": 83920}, {"from": 83919, "to": 83921}, {"from": 83917, "to": 83919}, {"from": 83918, "to": 83919}, {"from": 83916, "to": 83917}, {"from": 83916, "to": 83918}, {"from": 83915, "to": 83916}, {"from": 83913, "to": 83915}, {"from": 83914, "to": 83915}, {"from": 83912, "to": 83913}, {"from": 83912, "to": 83914}, {"from": 83910, "to": 83912}, {"from": 83911, "to": 83912}]}' | vg view -Jv - >boom1.vg
vg view -dA <(vg align -s GCGGTTTATGCGGCTACTTACTGTATTTTCTTTTTTTAAATTTCCTGTTTTGTTTTACTTTGGAAATGCATGATGGTTATACTACAG -p boom1.vg) boom1.vg | dot -Tpdf -o boom.
[boom.pdf](https://github.com/vgteam/vg/files/627159/boom.pdf)
pdf
```

Now look at `boom.pdf`.

If we compare the sequence of the alignment to the sequence traced through the graph, there is an additional one base match at the end.

**Comment by jeizenga** [comment]
@ekg The problem was in the translation from gssw_graph_mappings to protobuf Alignments--there was a weird interaction with the way I hacked gssw to allow it to chose a node to align to pin to. Should be fixed with these PRs.

**Comment by ekg** [comment]
I broke this up into sections so it's a little easier to follow.

_****In short: awesome, this does the trick! I'll move to the paper tests now.****_

_****But:****_ We are still blocked on the OSX build, so I can't merge this yet.

## test harness

@jeizenga  Looks like your fix worked for the test I'm throwing at it.

If you'd like to reproduce the full test (now possible 'cuz I'm building to this 

```
vg construct -r 1mb1kgp/z.fa -v 1mb1kgp/z.vcf.gz -m 32 -p >z.vg
vg index -x z.xg z.vg
cat <(vg mod -pl 16 -e 4 z.vg ) <(vg mod -N z.vg) | pv | vg kmers -gB -k 16 -H 1000000000 -T 1000000001 - >z.smooth.graph 2>err
vg index -i z.smooth.graph -g z.gcsa -X 2 -Z 400 -p
vg sim -n 10000 -l 100 -e 0.005 -e 0.001 -x z.xg -s 9999 -a | pv >z.sim.10k
vg sim -n 10000 -l 100 -e 0.01 -e 0.005 -x z.xg -s 9999 -a | pv >z.sim.10k.e1
```

Now we can run alignment tests:

```
vg map -x z.xg -g z.smooth.gcsa -G z.sim.10k -J -t 4 -a --compare | pv -l | cut -f 2 | histogram.py
```

This will print a little distribution of the alignment/realignment overlap scores produced by the `vg map --compare` routine.

```
-> % vg map -x z.xg -g z.smooth.gcsa -G z.sim.10k -J -t 4 -a --compare | pv -l | cut -f 2 | histogram.py 
  10k 0:00:01 [5.19k/s] [       <=>                                                                                                                                                                                 ]
# NumSamples = 10000; Min = 0.00; Max = 1.00
# Mean = 0.993345; Variance = 0.006267; SD = 0.079162; Median 1.000000
# each ∎ represents a count of 132
    0.0000 -     0.1000 [    62]: 
    0.1000 -     0.2000 [     1]: 
    0.2000 -     0.3000 [     0]: 
    0.3000 -     0.4000 [     1]: 
    0.4000 -     0.5000 [     0]: 
    0.5000 -     0.6000 [     0]: 
    0.6000 -     0.7000 [     0]: 
    0.7000 -     0.8000 [     0]: 
    0.8000 -     0.9000 [     6]: 
    0.9000 -     1.0000 [  9930]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
```

[`histogram.py`](https://raw.githubusercontent.com/bitly/data_hacks/master/data_hacks/histogram.py)

## full length bonus: mission accomplished

The pinning and full length bonus do the right thing. Previously, when using local alignment for the tails, I saw a drop in overlap score when aligning higher error rate reads (1%) relative to (0.5%). This was more pronounced for the mem threader than the old mapper. Something like a .2% fall in alignment identity.

This effect can be shown on this branch by turning off the full length bonus (note: using this branch at this comment):

With lower error:

```
-> % vg map -x z.xg -g z.smooth.gcsa -G z.sim.10k -J -t 4 -a -T 0 --compare | pv -l | cut -f 2 | histogram.py | grep Mean
  10k 0:00:02 [4.82k/s] [           <=>                                                                                                                                                                             ]
# Mean = 0.992923; Variance = 0.006285; SD = 0.079278; Median 1.000000
```

With higher error:

```
-> % vg map -x z.xg -g z.smooth.gcsa -G z.sim.10k.e1 -J -t 4 -a -T 0 --compare | pv -l | cut -f 2 | histogram.py | grep Mean
  10k 0:00:03 [ 3.3k/s] [              <=>                                                                                                                                                                          ]
# Mean = 0.991341; Variance = 0.005708; SD = 0.075554; Median 1.000000
```

This effect doesn't happen when we turn the bonus back on:

```
-> % vg map -x z.xg -g z.smooth.gcsa -G z.sim.10k -J -t 4 -a -T 5 --compare | pv -l | cut -f 2 | histogram.py | grep Mean
  10k 0:00:02 [4.72k/s] [           <=>                                                                                                                                                                             ]
# Mean = 0.993345; Variance = 0.006267; SD = 0.079162; Median 1.000000
```

```
erik@tappy [02:14:25 PM] [~/vg.8/test] [master *]
-> % vg map -x z.xg -g z.smooth.gcsa -G z.sim.10k.e1 -J -t 4 -a -T 5 --compare | pv -l | cut -f 2 | histogram.py | grep Mean
  10k 0:00:03 [3.27k/s] [              <=>                                                                                                                                                                          ]
# Mean = 0.993250; Variance = 0.005811; SD = 0.076229; Median 1.000000
```

Not a big difference in terms of the overall metric, but in terms of the error rate this is huge.

Without 

```
> 0.992923 - 0.991341
[1] 0.001582
```

With:

```
> 0.993345 - 0.993250
[1] 9.5e-05
```

The local alignment error rate is 22% lower in the new version as compared to the old when aligning reads with ~1% simulated sequencing error.

```
> 1- ((1-0.993250) / (1-0.991341))                                                                                                                                                                                   
[1] 0.2204643
```

It is 6% lower with the ~0.5% simulated sequencing error:

```
> 1- ((1-0.993345) / (1-0.992923))
[1] 0.05962979
```


## improvement over default

Now the mem threader (`vg map -a`) is doing nearly as well on the low error rate data and slightly better than the current default (`vg map`) on the higher error rate data.

For the low simulated error rate alignments we get

threader: 0.993345,
```
-> % vg map -x z.xg -g z.smooth.gcsa -G z.sim.10k -J -t 4 -a --compare | pv -l | cut -f 2 | histogram.py | grep Mean   
  10k 0:00:02 [4.86k/s] [           <=>                                                                                                                                                                             ]
# Mean = 0.993345; Variance = 0.006267; SD = 0.079162; Median 1.000000
```

default: 0.993728
```
-> % vg map -x z.xg -g z.smooth.gcsa -G z.sim.10k -J -t 4 --compare | pv -l | cut -f 2 | histogram.py | grep Mean 
  10k 0:00:04 [2.23k/s] [                  <=>                                                                                                                                                                      ]
# Mean = 0.993728; Variance = 0.005778; SD = 0.076010; Median 1.000000
```

For the higher error rate we get

threader: 0.993250

```
-> % vg map -x z.xg -g z.smooth.gcsa -G z.sim.10k.e1 -J -t 4 -a --compare | pv -l | cut -f 2 | histogram.py | grep Mean
  10k 0:00:03 [3.26k/s] [              <=>                                                                                                                                                                          ]
# Mean = 0.993250; Variance = 0.005811; SD = 0.076229; Median 1.000000
```

default: 0.992775.

```
-> % vg map -x z.xg -g z.smooth.gcsa -G z.sim.10k.e1 -J -t 4  --compare | pv -l | cut -f 2 | histogram.py | grep Mean 
  10k 0:00:09 [1.06k/s] [                                    <=>                                                                                                                                                    ]
# Mean = 0.992775; Variance = 0.005261; SD = 0.072531; Median 1.000000
```

Note that the runtime is also much better for the threader. It's >3X as fast in 1% simulated error and >2X as fast in 0.5% simulated error.

**Comment by jeizenga** [comment]
Nice! I did notice that some of the CI is failing in genotype tests, which is something I touched in those dirty commits that somehow got into my pinned alignment branch. I'm going to look into it to make sure I didn't break something.

**Comment by ekg** [comment]
Cool, let me know what to do. This and the OSX build then are what's
blocking the merge.

**Comment by jeizenga** [comment]
@ekg https://github.com/vgteam/vg/pull/584 resolves the genotype test failures, but some msga tests are also failing. Seems they're having an indexing error in sdsl somwhere. Does msga have any dependencies on the Aligner or anything we've changed here?

**Comment by ekg** [comment]
@jeizenga @edawson @adamnovak @glennhickey --- I would love to merge this but can't figure out what's going on with the OSX build.

**Comment by adamnovak** [comment]
Right now the Linux build is broken because the tests fail (there's an invalid option being used on genotype, apparently).

The OS X build can't install GCC; maybe something is down on Homebrew's end?

**Comment by adamnovak** [comment]
I've restarted the OS X build to see if it manages to install GCC this time.

**Comment by jeizenga** [comment]
Also, reminder: that PR a few comments back fixes the genotype test failures, but not the msga test failures. The msga tests that are failing seem to be looking for a particular checksum from the graph that gets produced, so my guess is that the changes to the underlying alignment algorithm are producing something that's slightly different.

**Comment by jeizenga** [comment]
Also also, where does the script that Travis uses live? I just tried the same commands its using on my Mac and got the same error. The problem seems to be "brew unlink gcc". My machine has a gcc49 cellar, but no gcc cellar: gcc is /opt/local/bin, not /usr/local/Cellar. Maybe it's the same thing that's causing the error?

**Comment by ekg** [comment]
@jeizenga the msga failures seem to be caused by the changes to the traceback and the pinning. Now, the "null node" which is used to tie together all the nodes in the graph is getting alignments to it. This is a problem and causes the failures I'm seeing. I'm not sure we need this node....

**Comment by ekg** [comment]
The pre-merge is failing and the only reason I can come up with is that it's using the lib/ cache from travis.

Post-merge is fine.

I'm going to merge into master and cross my fingers.

**Comment by ekg** [comment]
@jeizenga I'm seeing further improvement of the MEM threader over the old default now at all levels of error since implementing the correct score function including the full length bonus!

**Pull request merged**
