### PR TITLE
MSA constructor for graphs

### PR DESCRIPTION
**Pull request by jeizenga**
I made an algorithm to build graphs from MSAs for the CPANG course. Some of it already got merged but here's a slightly more polished version with unit tests.

### CODE REVIEW

**Comment by jeizenga** [comment]
Jenkins, test this please.

**Comment by ekg** [comment]
Has this been pulled in to master now?

**Comment by jeizenga** [comment]
No, but it's mostly just unit tests. The actual constructors were pulled in
through your CPANG branch.

**Comment by ekg** [comment]
Ok let's get the unit tests in too.

**Comment by adamnovak** [comment]
We still want this, right?

Jenkins, test this please.

**Pull request merged**
