### PR TITLE
Improve GBWT use in vg map

### PR DESCRIPTION
**Pull request by adamnovak**
Now we can get the total haplotype count from the XG, which is more or less the number Yohei's code wants.

I also added a flag to reads so you can tell if their scores are corrected.

I am also now allowing score correction even when some mappings have no paths, because it turns out that happens a lot.

With these changes I am able to correct (and see that I can correct) about 93% of read pairs and 96% of single reads, in my testing on snp1kg MHC.

### CODE REVIEW

**Comment by adamnovak** [comment]
@jeizenga This includes my XG changes to allow it to hold a haplotype count; right now it just assumes all the samples are diploid and counts 2 * the number of samples in the input VCF. You also need to build your GBWT and XG in the same vg index run.

**Comment by glennhickey** [comment]
Jenkins, test this please.

**Comment by adamnovak** [comment]
It looks like the last merge to master got an anomalously high F1 of 0.9302 and now it won't accept the 0.9225 that we used to get.

I can't replicate the higher F1 when running the master branch myself. I'm going to merge this in and delete the existing baseline for that test so it makes a new one:

```
aws s3 rm s3://cgl-pipeline-inputs/vg_cgl/vg_ci/jenkins_regression_baseline/outstore-BRCA2-primary/NA12878_vcfeval_output_f1.txt
```

**Comment by adamnovak** [comment]
Actually, I am just going to push the baseline back:

```
echo 0.9225 > baseline.txt

aws s3 cp --acl public-read ./baseline.txt s3://cgl-pipeline-inputs/vg_cgl/vg_ci/jenkins_regression_baseline/outstore-BRCA2-primary/NA12878_vcfeval_output_f1.txt 
```

**Comment by adamnovak** [comment]
Hm. Looks like it got the higher value this time. Did you do something @glennhickey ?

**Comment by glennhickey** [comment]
Not sure what's going on.  As far as I can tell, it's randomly bouncing
back and forth.  I'll assume due to minor differences in the GAM output.
Weird that it just started happening.

**Pull request merged**
