### PR TITLE
Drop some graphs now covered by the comparison runner

### LINKED ISSUE #1017: Remove some graphs from the Jenkins tests
We're wasting time running comparisons between graphs in the guise of regression tests. We should compare our graphs with separate experiments.

### PR DESCRIPTION
**Pull request by adamnovak**
Closes #1017.

We need to look out for missing graphs that were supposed to run manually, now, since I turned off the assertion that we didn't lose any.

### CODE REVIEW

**Comment by adamnovak** [comment]
@jeizenga Should I care that the mpmap tests failed?

**Comment by jeizenga** [comment]
I don't think so. One of them seems to be that weirdness where perfect classification gives 0 AUC, the other one doesn't even look like it has a baseline.

**Comment by adamnovak** [comment]
@jeizenga How did the test get into master without getting a baseline?

**Comment by jeizenga** [comment]
Beats me

**Comment by adamnovak** [comment]
OK, I will try and fix these tests; they're failing for every PR and upsetting Jenkins.

**Comment by adamnovak** [comment]
OK it looks like the baseline is never updated if the tests fail. So you need to make sure the tests pass in your PR, without a baseline, because if they don't pass in the PR they're *not* going to pass later on master.

**Comment by adamnovak** [comment]
Travis macs are still hosed, but everything else seems happy with this change. I'm going to merge it in.

**Pull request merged**
