### PR TITLE
More robust dot layout

### PR DESCRIPTION
**Pull request by buske**
* Updated HTML-based ports for more robust dot layout (avoids spline triangulation complaints associated with simple compass point ports)
* Removes rank-constraint from path edges, which results in qualitatively nicer graphs.

### CODE REVIEW

**Comment by ekg** [comment]
Woah, I should have checked this out before merging. I can't quite figure out how you're getting this to work. This is what I get:

image

Here's the json version of the graph:

```
{"path": [{"name": "0132043e85f348472", "mapping": [{"position": {"node_id": 32, "is_reverse": true}, "edit": [{"to_length": 19, "from_length": 19}], "rank": 1}, {"position": {"node_id": 18, "is_reverse": true}, "edit": [{"to_length": 1, "from_length": 1}], "rank": 2}, {"position": {"node_id": 5, "is_reverse": true}, "edit": [{"to_length": 1, "from_length": 1}], "rank": 3}, {"position": {"node_id": 3, "is_reverse": true}, "edit": [{"to_length": 1, "from_length": 1}], "rank": 4}, {"position": {"node_id": 17, "is_reverse": true}, "edit": [{"to_length": 3, "from_length": 3}], "rank": 5}, {"position": {"node_id": 16, "is_reverse": true}, "edit": [{"to_length": 5, "from_length": 5}], "rank": 6}]}, {"name": "0781c5007103a17f1", "mapping": [{"position": {"node_id": 30, "is_reverse": true}, "edit": [{"to_length": 12, "from_length": 12}], "rank": 1}, {"position": {"node_id": 22, "is_reverse": true}, "edit": [{"to_length": 2, "from_length": 2}], "rank": 2}, {"position": {"node_id": 20, "is_reverse": true}, "edit": [{"to_length": 4, "from_length": 4}], "rank": 3}, {"position": {"node_id": 7, "is_reverse": true}, "edit": [{"to_length": 1, "from_length": 1}], "rank": 4}, {"position": {"node_id": 19, "is_reverse": true}, "edit": [{"to_length": 2, "from_length": 2}], "rank": 5}, {"position": {"node_id": 18, "is_reverse": true}, "edit": [{"to_length": 1, "from_length": 1}], "rank": 6}, {"position": {"node_id": 4, "is_reverse": true}, "edit": [{"to_length": 1, "from_length": 1}], "rank": 7}, {"position": {"node_id": 31, "is_reverse": true}, "edit": [{"to_length": 7, "from_length": 7}], "rank": 8}]}, {"name": "0b886c55a95eb4bd3", "mapping": [{"position": {"node_id": 17}, "edit": [{"to_length": 3, "from_length": 3}], "rank": 1}, {"position": {"node_id": 2}, "edit": [{"to_length": 1, "from_length": 1}], "rank": 2}, {"position": {"node_id": 4}, "edit": [{"to_length": 1, "from_length": 1}], "rank": 3}, {"position": {"node_id": 18}, "edit": [{"to_length": 1, "from_length": 1}], "rank": 4}, {"position": {"node_id": 19}, "edit": [{"to_length": 2, "from_length": 2}], "rank": 5}, {"position": {"node_id": 8}, "edit": [{"to_length": 1, "from_length": 1}], "rank": 6}, {"position": {"node_id": 20}, "edit": [{"to_length": 4, "from_length": 4}], "rank": 7}, {"position": {"node_id": 29}, "edit": [{"to_length": 17, "from_length": 17}], "rank": 8}]}, {"name": "769bfb32b4249c715", "mapping": [{"position": {"node_id": 28}, "edit": [{"to_length": 21, "from_length": 21}], "rank": 1}, {"position": {"node_id": 25}, "edit": [{"to_length": 7, "from_length": 7}], "rank": 2}, {"position": {"node_id": 10}, "edit": [{"to_length": 1, "from_length": 1}], "rank": 3}, {"position": {"node_id": 26}, "edit": [{"to_length": 1, "from_length": 1}], "rank": 4}]}, {"name": "x", "mapping": [{"position": {"node_id": 16}, "edit": [{"to_length": 5, "from_length": 5}], "rank": 1}, {"position": {"node_id": 17}, "edit": [{"to_length": 3, "from_length": 3}], "rank": 2}, {"position": {"node_id": 2}, "edit": [{"to_length": 1, "from_length": 1}], "rank": 3}, {"position": {"node_id": 4}, "edit": [{"to_length": 1, "from_length": 1}], "rank": 4}, {"position": {"node_id": 18}, "edit": [{"to_length": 1, "from_length": 1}], "rank": 5}, {"position": {"node_id": 19}, "edit": [{"to_length": 2, "from_length": 2}], "rank": 6}, {"position": {"node_id": 7}, "edit": [{"to_length": 1, "from_length": 1}], "rank": 7}, {"position": {"node_id": 20}, "edit": [{"to_length": 4, "from_length": 4}], "rank": 8}, {"position": {"node_id": 22}, "edit": [{"to_length": 2, "from_length": 2}], "rank": 9}, {"position": {"node_id": 24}, "edit": [{"to_length": 6, "from_length": 6}], "rank": 10}, {"position": {"node_id": 25}, "edit": [{"to_length": 7, "from_length": 7}], "rank": 11}, {"position": {"node_id": 10}, "edit": [{"to_length": 1, "from_length": 1}], "rank": 12}, {"position": {"node_id": 26}, "edit": [{"to_length": 1, "from_length": 1}], "rank": 13}, {"position": {"node_id": 27}, "edit": [{"to_length": 3, "from_length": 3}], "rank": 14}, {"position": {"node_id": 13}, "edit": [{"to_length": 1, "from_length": 1}], "rank": 15}, {"position": {"node_id": 15}, "edit": [{"to_length": 11, "from_length": 11}], "rank": 16}]}], "node": [{"sequence": "CAAAT", "id": 16}, {"sequence": "AAG", "id": 17}, {"sequence": "G", "id": 2}, {"sequence": "A", "id": 3}, {"sequence": "T", "id": 5}, {"sequence": "C", "id": 4}, {"sequence": "T", "id": 18}, {"sequence": "TG", "id": 19}, {"sequence": "G", "id": 7}, {"sequence": "A", "id": 8}, {"sequence": "AAAT", "id": 20}, {"sequence": "TT", "id": 22}, {"sequence": "TCTGGA", "id": 24}, {"sequence": "ATCTGGAGTCTCTATAA", "id": 29}, {"sequence": "CCGGAATTCTAT", "id": 30}, {"sequence": "GGAAATCTGTGGAGTCTAT", "id": 32}, {"sequence": "GTTCTAT", "id": 25}, {"sequence": "T", "id": 10}, {"sequence": "A", "id": 11}, {"sequence": "A", "id": 26}, {"sequence": "TAT", "id": 27}, {"sequence": "T", "id": 13}, {"sequence": "A", "id": 14}, {"sequence": "CCAACTCTCTG", "id": 15}, {"sequence": "AAACTTAGACATTTTTCCAGT", "id": 28}, {"sequence": "AAATAGT", "id": 31}], "edge": [{"from": 16, "to": 17}, {"from": 17, "to": 2}, {"from": 2, "to": 4}, {"from": 2, "to": 5}, {"from": 17, "to": 3}, {"from": 3, "to": 4}, {"from": 3, "to": 5}, {"from": 5, "to": 18}, {"from": 4, "to": 31, "from_start": true, "to_end": true}, {"from": 4, "to": 18}, {"from": 18, "to": 19}, {"from": 32, "to": 18, "from_start": true, "to_end": true}, {"from": 19, "to": 7}, {"from": 7, "to": 20}, {"from": 19, "to": 8}, {"from": 8, "to": 20}, {"from": 20, "to": 22}, {"from": 20, "to": 29}, {"from": 22, "to": 24}, {"from": 30, "to": 22, "from_start": true, "to_end": true}, {"from": 24, "to": 25}, {"from": 28, "to": 25}, {"from": 25, "to": 10}, {"from": 10, "to": 26}, {"from": 25, "to": 11}, {"from": 11, "to": 26}, {"from": 26, "to": 27}, {"from": 27, "to": 13}, {"from": 13, "to": 15}, {"from": 27, "to": 14}, {"from": 14, "to": 15}]}
```

Rendering with `vg -dp` on linux. It looks like the port hack you did with HTML tables doesn't work in my environment?

**Comment by buske** [comment]
Crap. Thanks for the example. I don't think any of the testing examples I was using had reverse edges, actually, so it's possible something is mixed up there. Taking a look now. Sorry!

**Comment by ekg** [comment]
There aren't reversing edges... It looks like one commit changed headport
to tailport. I have a fix.

**Comment by buske** [comment]
Ack, sloppiness on my part when doing the rebase.

**Comment by buske** [comment]
Indeed, 07400cd introduced the bug. Here's the patch to fix.
```
diff --git a/src/vg.cpp b/src/vg.cpp
index 7b35762..862e9a2 100644
--- a/src/vg.cpp
+++ b/src/vg.cpp
@@ -6572,10 +6572,10 @@ void VG::to_dot(ostream& out, vector<Alignment> alignments,
             if ((!invert_edge_ports && e->to_end())
                 || (invert_edge_ports && !e->to_end())) {
                 out << "arrowhead=none,";
-                out << "tailport=se,";
+                out << "headport=se,";
             } else {
                 out << "arrowhead=none,";
-                out << "tailport=nw,";
+                out << "headport=nw,";
             }
             out << "penwidth=2,";
```

Also, I separated the commit d46ea5d in case you wanted to exclude it for stylistic reason. With the commit, the layout is much more linear, but the paths sometimes interweave with the reference.

**Comment by ekg** [comment]
We could optionally enable it. But we are running out of options!

**Comment by ekg** [comment]
That's exactly the fix I've written on my end. I'll commit and push here.

**Comment by ekg** [comment]
Your changes are AWESOME @buske:

image

Here's some cyclic stuff:

image

I wonder why we see the gaps in this but not the other. I really don't mind. It's clear what's going on and that's the main objective here.

**Pull request merged**
