### PR TITLE
Add identity field to Alignments from mpmap

### PR DESCRIPTION
**Pull request by jeizenga**
`vg call` likes Alignments with the identity field filled out, so I added it into `vg mpmap`.

### CODE REVIEW

**Comment by glennhickey** [comment]
The test failures seem completely unrelated.  Is this just vg map being
non-deterministic?

**Comment by ekg** [comment]
It could be something I pushed into master.

**Comment by jeizenga** [comment]
Hmm. I don't see how that would have happened if you didn't change something in vg call. How are the identities used in vg call?

**Comment by glennhickey** [comment]
There's an identity filter that's on by default in toil-vg that affects
calling.  It's turned off explicitly in test_map_brca1_snp1kg_mpmap now.

But it seems that Erik modified vg map directly in master (ie without going
through a PR) in a way that makes this test fail.  If this is the case,
then the next PR (ie this one) would be guaranteed to fail this test
regardless of the PR's contents.

**Pull request merged**
