### PR TITLE
Handlify haplotype extracter and expand context

### PR DESCRIPTION
**Pull request by jeizenga**
I handlified the `HaplotypeExtracter`. It still has some Protobuf bits that feel dated, but I think that it's the primary interface for SequenceTubeMaps and I don't want to break that. 

Of note, as part of this I wrote a handle-based replacement for `expand_context` that I think could replace the equivalent method in both `XG` and `VG`. However, the semantics are ever-so-slightly different, but in a way that I think makes it more well-defined. Accordingly, I'm not going through to replace calls to the old versions yet.

### CODE REVIEW

**Comment by jeizenga** [comment]
@adamnovak I have some failing builds using GCC, which seem to have something to do with htslib. I see you made some changes involving htslib in https://github.com/vgteam/vg/pull/2365. Does this look like it might have anything to do with those?

**Comment by adamnovak** [comment]
I think the problem might be that your build is running off of master's cache, but without either master's updated htslib or the code I added to the Makefile to clean out the old htslib headers before building the new htslib. So the cached headers are getting into your htslib build and breaking it. You should merge master into your branch, and it will solve the problem.

**Comment by ekg** [comment]
Jordan, check out subgraph.cpp in algorithms.

**Comment by jeizenga** [comment]
Hmm. Yeah, I think those functions could probably be composed in the right way to get something pretty close to the semantics I was trying to copy from XG's `expand_context`. That probably could have saved me some time...

**Pull request merged**
