### PR TITLE
Count support for shared nodes as half

### PR DESCRIPTION
**Pull request by adamnovak**
This may help with the problems @glennhickey was encountering.

### CODE REVIEW

**Comment by adamnovak** [comment]
@glennhickey Does this make our calling better or worse? Jenkins is supposed to tell me that, right? Where do I find its conclusions?

**Comment by glennhickey** [comment]
Sorry, I got lost down a git hole chasing noise, and don't have anything
conclusive for this yet.  I'll have results for the cases I was looking at
on chr21 by first thing tomorrow.

The jenkins test results are here

http://jenkins.cgcloud.info/job/vg/43/testReport/jenkins.vgci/VGCITest/

Click any test and look at the standard output section,  ex mhc snp1kg is
here:

http://jenkins.cgcloud.info/job/vg/43/testReport/jenkins.vgci/VGCITest/test_map_mhc_snp1kg/
Standard out is this:

F1: 0.8608  Baseline: 0.8607  Threshold: 0.02

So it's saying a 0.0001 F1 boost over last successful build.  Most tests
are identical.  The threshold of 0.02 is what's used to see if the test
passed, and really needs to be tightened now.

**Comment by glennhickey** [comment]
This change fixes the example I sent, but is having surprisingly little
impact on my chr21 tests.  Digging into it now.

Freebayes/samtools/platypus calls are just about ready for surjected bams,
which will be quite interesting too.

**Comment by adamnovak** [comment]
It looks like it has almost no effect on the results in the tests, so I am going to merge this in.

**Pull request merged**
