### PR TITLE
Remove RocksDB index

### PR DESCRIPTION
**Pull request by jeizenga**
## Changelog Entry
To be copied to the [draft changelog](https://github.com/vgteam/vg/wiki/Draft-Changelog) by merger:

* `rocksdb` is no longer a dependency.
* `vg index` no longer will produce RocksDB indexes of GAMs or graphs.
* `vg find` can no longer be used to query from RocksDB indexes.
* `vg genotype` no longer accepts RocksDB GAM indexes, and instead accepts only GAMs.
* `vg gamsort` can no longer sort using the RocksDB order.
* `vg compare` has been removed.
* `vg locify` has been removed.

## Description

Thie PR completely removes the RocksDB dependency. It was mostly unused at this point, but there were a few straggler subcommands. If we want to retain the same functionality with them, they will need to be updated to use the `.gai` index from `gamsort`:
* `vg genotype` could optionally use the RocksDB read index, but now only accepts GAMs
* `vg locify` is fully dependent on the RocksDB index to produce sensible input, but it seems to be essentially unmaintained since ~2016. I think this command is a good candidate for being deleted, but this PR just leaves it nonfunctional. **Edit: I deleted it.**

### CODE REVIEW

**Comment by adamnovak** [comment]
I don't think we want to say locify is "crippled".

**Comment by jeizenga** [comment]
I could just delete it, but as is on this PR it can't produce sensible results.

**Comment by adamnovak** [comment]
No I mean more that it's ableist.

If it doesn't work, we also should rip it out.

**Comment by jeizenga** [comment]
Got it, language is updated and it is deleted.

**Comment by adamnovak** [comment]
@jeizenga I merged the other deprecating PR so now this conflicts on the removed commands.

**Pull request merged**
