### PR TITLE
Sim from paths

### LINKED ISSUE #1167: Implement simulation from paths
Part of #1147, and also probably important for #1166.

### PR DESCRIPTION
**Pull request by adamnovak**
Closes #1167 

Allows you to specify `-P path_name` and restrict vg sim to reads that follow a path.

This isn't just the subset of the graph covered by the path; it correctly accounts for cycles.

Right now the changes to the trained simulator need the most testing (because I haven't tested them).

### CODE REVIEW

**Comment by arkal** [comment]
Jenkins, test this please.

@adamnovak i'm sorry i accidentally killed your instance running this test.

**Comment by adamnovak** [comment]
The trained simulator seems to be working fine.

**Comment by ekg** [comment]
Ideally we could take a list of paths or a path prefix so that we could simulate from all of them without bias. What do you think?

**Comment by adamnovak** [comment]
That would be nice; we'd have to change the simulator to keep a bit of
state to know which path it's working on. But if we did that we could
weight the paths by length correctly.

**Pull request merged**
