### PR TITLE
Use latest toil-vg in Gitlab tests

### PR DESCRIPTION
**Pull request by glennhickey**
Bumps the tests from Python2.7 to Python3.6 in the process

### CODE REVIEW

**Comment by adamnovak** [comment]
@glennhickey I'm going to try turning on a Kubernetes runner on our Gitlab. It will probably cause the Gitlab tests here to fail unless you pull in the last PR I merged into master, which does some hosuekeeping that ought to let the tests pass on Kubernetes.

**Comment by glennhickey** [comment]
OK, thanks for the heads up.  I've rebased.  This PR is pretty low priority so no worries if it's delayed due to gitlab work...

**Comment by adamnovak** [comment]
This is still broken @glennhickey, but not for Kubernetes-related reasons now, I don't think.

You can go ahead and fix the remaining bugs, or I could give it a shot.

**Comment by glennhickey** [comment]
Thanks @adamnovak I'll take a look today.

**Pull request merged**
