### PR TITLE
Update to latest vcflib

### PR DESCRIPTION
**Pull request by adamnovak**
This updates to current vcflib, slightly patched to fix some missing return
statements.

This fixes half of #2733 by getting rid of the `-lvcflib` in vcflib, because
the new vcflib has a completely new CMake build system.

It can't be instructed to use vg's HTSlib (see
https://github.com/vcflib/vcflib/issues/286), but apparently it uses a similar
enough HTSlib that I can get it to build and run tests.

### CODE REVIEW

**Comment by adamnovak** [comment]
It looks like builds are failing because of crosstalk between vg's HTSlib headers and vcflib's bundled HTSlib build.

I think the only real right thing to do is, if vcflib has to bundle htslib, then vg has to use that htslib instead of its own.

**Comment by adamnovak** [comment]
I'm taking a different approach and trying to use vcflib's htslib as the One True HTSlib for the build. This PR can't pass until https://github.com/vcflib/vcflib/pull/289 is merged, which can't happen until it passes its tests, which in turn will require https://github.com/ekg/tabixpp/pull/22 being merged.

**Comment by mr-c** [comment]
Hello @adamnovak ; can this be merged?

**Comment by adamnovak** [comment]
Yes. I was holding off because I wanted to make a release for the Giraffe paper before I started messing about with removing our htslib, but now that's done so we can merge this.

**Comment by mr-c** [comment]
Thanks!

**Pull request merged**
