### PR TITLE
Block the stream

### PR DESCRIPTION
**Pull request by adamnovak**
This is my attempt to move vg over to blocked-gzip compression, instead of just gzip compression, to facilitate GAM indexing for #1792.

So far I have managed to get the output to be in blocked gzip format. I've also refactored things a bit so that stream.hpp isn't such a common transitive include, and so that we don't use the group lengths for progress reporting anymore (since they didn't represent the whole file).

I still have to run the input data through BGZF (probably along with format autodetection), and expose some sensible interface to allow for seeking and for recording offsets.

### CODE REVIEW

**Comment by ekg** [comment]
Have you considered other non-zlib based compressors?

**Comment by adamnovak** [comment]
No, not really. If we're willing to make breaking changes, that opens up a lot of options (like dropping the group length field). But if we use blocked GZIP, the resulting files are still readable by older versions of vg, since they're still GZIP files.

**Comment by adamnovak** [comment]
I think that once I get this passing all the tests, it will be ready to merge.

I've had to point at an htslib fork, because being backwards-compatible depends on https://github.com/samtools/htslib/pull/744 being in htslib, to give it multi-member gzip read support.

**Comment by adamnovak** [comment]
I'm going to go ahead and merge this.

As a side effect of the changes I had to make to htslib, we also have a newer htslib being used here. This gives us support for `libdeflate` as a compression library instead of zlib, for blocked gzip files. It uses the same format, but is supposed to be much faster. So we could potentially boost our IO speed by pulling `libdeflate` into the build process, either as a submodule or as a package dependency.

**Pull request merged**
