### PR TITLE
Deactivate recursive sub-MEM finding in mpmap

### PR DESCRIPTION
**Pull request by jeizenga**
It's all in the name.

### CODE REVIEW

**Comment by jeizenga** [comment]
Jenkins, test this please.

**Comment by ekg** [comment]
@jeizenga what problem did you run into?

**Comment by jeizenga** [comment]
Just made things slower without a noticeable improvement in accuracy

**Comment by ekg** [comment]
I've just checked and see the same thing on a test vs. the yeast SGRP2 pangenome.

**Pull request merged**
