### PR TITLE
update to latest libbdsg

### PR DESCRIPTION
**Pull request by mr-c**
## Changelog Entry
To be copied to the [draft changelog](https://github.com/vgteam/vg/wiki/Draft-Changelog) by merger:

 * Update to latest libbdsg to gain non-x86 compatability

### CODE REVIEW

**Comment by mr-c** [comment]
FYI: There were a lot of other changes in libbdsg that I am unqualified to summarize in the changelog

**Comment by adamnovak** [comment]
Gitlab CI failed on this because Quay was down for maintenance or something and couldn't take pushes. The cloud is built on sand and the entire Internet as we know it is never more than twenty minutes from total collapse.

I've rerun it; it will probably pass.

**Comment by mr-c** [comment]
Thanks @adamnovak , "All checks have passed"!

**Comment by mr-c** [comment]
It passed! Ready for review and merge

**Comment by mr-c** [comment]
Thank you @jeizenga !

**Pull request merged**
