### PR TITLE
TravisCI: turn on ccache

### PR DESCRIPTION
**Pull request by mr-c**
As per https://docs.travis-ci.com/user/caching/#ccache-cache

### CODE REVIEW

**Comment by mr-c** [comment]
This appears to be working!

**Comment by mr-c** [comment]
ping :-)

**Comment by jeizenga** [comment]
Not sure why it isn't posting here, but we seem to have problems with the Mac Travis build still:
https://travis-ci.org/vgteam/vg/builds/645577607?utm_medium=notification&utm_source=email

**Comment by mr-c** [comment]
@jeizenga Okay, I simplified this PR to be just the `ccache: true`, nothing else.

**Comment by mr-c** [comment]
Can someone with permissions push the "restart" button on https://travis-ci.org/vgteam/vg/jobs/646066446 ? Seems like a transient error.

**Pull request merged**
