### PR TITLE
Update to latest xg and DYNAMIC

### LINKED ISSUE #267: vg index: xg construction memory usage increase
I'm noticing memory usage in `vg index` to build the xg index has increased quite a lot in the last few weeks. Previously and for a long time, this operation maxed out at roughly 200 GiB of RAM on the whole-genome 1000G graph. Now I see it blowing through the machine's 244 GiB. Is this expected, anything to be done?

(Edited to remove misleading reference to gcsa2)
(Edited to remove misleading reference to 435c97c)

### PR DESCRIPTION
**Pull request by adamnovak**
Fixes #267, hopefully, by not pulling in all paths as succinct threads by default in `vg index`.

### CODE REVIEW

**Comment by ekg** [comment]
Seems this broke master when I merged it. Will deal with tomorrow.

**Comment by adamnovak** [comment]
Looks like the RDF export broke somehow? But only in the merge commit.
Weird.

**Comment by ekg** [comment]
Maybe a change with Travis? Weird stuff.

**Comment by ekg** [comment]
@adamnovak sorry, it didn't break it! The problem is with the superbubbly PR #259.

**Pull request merged**
