### PR TITLE
Add an interface to convert bed to gam

### PR DESCRIPTION
**Pull request by 6br**
In order to annotate a path with genes or repeats as a subpath, I propose to add an interface to convert BED format to GAM format.

It intends to work with commands below.

```
vg annotate -p -x input.xg -b input.bed > output.gam
vg mod -P --include-aln output.gam input.vg > output.vg
```

### CODE REVIEW

**Comment by adamnovak** [comment]
Jenkins, test this please.

**Comment by adamnovak** [comment]
```
src/alignment.cpp:1066:76: error: no matching function for call to ‘xg::XG::target_alignment(std::string&, size_t&, size_t&)’
             Alignment alignment = xgindex->target_alignment(seq, sbuf, ebuf);
                                                                            ^
src/alignment.cpp:1066:76: note: candidate is:
In file included from src/alignment.hpp:11:0,
                 from src/alignment.cpp:1:
src/xg.hpp:227:15: note: vg::Alignment xg::XG::target_alignment(const string&, size_t, size_t, const string&) const
     Alignment target_alignment(const string& name, size_t pos1, size_t pos2, const string& feature) const;
               ^
src/xg.hpp:227:15: note:   candidate expects 4 arguments, 3 provided
make: *** [obj/alignment.o] Error 1
```

Looks like there's an argument missing here in this call.

**Comment by 6br** [comment]
I will fix.

**Comment by adamnovak** [comment]
Jenkins test this please

**Comment by adamnovak** [comment]
Looks good to me

**Comment by adamnovak** [comment]
Jenkins why have you forsaken me

Jenkins looks good to me

Jenkins test this please

**Comment by glennhickey** [comment]
Jenkins, ok to test.

**Pull request merged**
