### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tanessav**
Added lz4 in brew install

### CODE REVIEW

**Comment by adamnovak** [comment]
Looks good to me

**Comment by adamnovak** [comment]
OK to test

**Comment by adamnovak** [comment]
Jenkins, test this please.

**Comment by adamnovak** [comment]
OK, now you're on the whitelist.

Jenkins, test this please.

**Comment by glennhickey** [comment]
Too late now, but it's "Jenkins, ok to test."

**Pull request merged**
