### PR TITLE
Tweak README

### PR DESCRIPTION
**Pull request by adamnovak**
Really I just want to see if we can pass the CI tests from a PR with no actual code changes.

### CODE REVIEW

**Comment by jeizenga** [comment]
Well, that's infuriating.

**Comment by adamnovak** [comment]
Sorry. But as far as I can tell, you touched something. Are you sure that map doesn't eventually call anything you touched?

**Comment by jeizenga** [comment]
I'm completely at a loss. The only thing in that PR are a handful of new functions in alignment.[ch]pp and multipath_alignment.[ch]pp, and then using those function in mpmap_main.cpp. I have no idea how that could affect the performance of map.

**Comment by adamnovak** [comment]
Can you replicate the issue running one of the affected tests locally? Maybe you can paste in one function at a time until it breaks or something.

**Pull request merged**
