### PR TITLE
Update ultrabubbles to latest version as used in paper

### PR DESCRIPTION
**Pull request by glennhickey**
Replace #488 which got derailed by git fail.

### CODE REVIEW

**Comment by shilpagarg** [comment]
I get this error in vg genotype:
vg: src/path.cpp:1274: vg::Path vg::trim_hanging_ends(const vg::Path&): Assertion `first_m < last_m || (first_m == last_m && first_e <= last_e)' failed.
Aborted

**Comment by glennhickey** [comment]
I'll fix this tomorrow.  Are you able to share the input data and command
line?

thanks

**Comment by shilpagarg** [comment]
Do you have access at Sanger farm? I can point you to data then.


*~/vg/bin/vg genotype vg file gam.index -C > loci*

**Comment by glennhickey** [comment]
I don't have access to that.  Could you please add

cerr << pb2json(p) << endl;

before the assert (src/path.cpp:1273), rerun, then send the last few paths
to get printed?  I'm probably missing an obvious edge case that doesn't
come up in any of my usual test graphs.

**Comment by shilpagarg** [comment]
here is the result:

{"mapping": [{"position": {"node_id": 1351801, "offset": 28, "is_reverse":
true}, "rank": 1, "edit": [{"from_length": 24, "to_length": 24}]},
{"position": {"node_id": 1351800, "is_reverse": true}, "rank": 2, "edit":
[{"from_length": 52, "to_length": 52}]}, {"position": {"node_id": 1351799,
"is_reverse": true}, "rank": 3, "edit": [{"from_length": 52, "to_length":
52}]}, {"position": {"node_id": 1351798, "is_reverse": true}, "rank": 4,
"edit": [{"from_length": 23, "to_length": 23}]}]}
{}
vg: src/path.cpp:1274: vg::Path vg::trim_hanging_ends(const vg::Path&):
Assertion `first_m < last_m || (first_m == last_m && first_e <= last_e)'
failed.
Aborted

**Comment by glennhickey** [comment]
Yeah, looks like the empty path is the issue.  I think it's just the assert
statement that's in error here, so commenting it out is a quick fix.  I'll
PR a fix in once I have a chance to run some tests.

**Comment by shilpagarg** [comment]
I get this error now, is it possible for you to fix these issues in vg
genotype. I am looking forward to use it.

Warning: duplicate alignment names present! Example:
DB9GZKS1:346:H5LCMBCXX:1:1109:3632:73214 1:N:0:GTAGAGGATCTCTCCG
VG::forwardize_breakpoints error: failure, position 324979+53 is not inside
node {"sequence": "TCCGGGGACTCTACGAGAACCCTTTGTCCTACTGATTAATTTTGTACTGA",
"id": 324979}
vg: src/vg.cpp:4541: std::map<long int, std::set<std::tuple<long int, bool,
long unsigned int> > > vg::VG::forwardize_breakpoints(const std::map<long
int, std::set<std::tuple<long int, bool, long unsigned int> > >&):
Assertion `false' failed.
Aborted

**Pull request merged**
