### PR TITLE
add presets in map/mpmap

### PR DESCRIPTION
**Pull request by ocxtal**
implementation for #2028

### CODE REVIEW

**Comment by ocxtal** [comment]
@adamnovak Thanks for comment. I fully agree with you and fixed the behavior to give priority to individual parameters. Unrecognized argument is now treated as an error.

@jeizenga I've merged the parser for -E/--long-read-scoring option to --preset for simplicity. I also made the long_read_scoring flag set for PacBio and Nanopore presets.  Which do you think is better for contig / asm{5,10,20} presets (set or not)?

**Comment by adamnovak** [comment]
I've updated this to agree with the latest master. We can probably go ahead and merge it if the tests pass.

**Comment by ekg** [comment]
@ocxtal sorry, I should have merged this in because I just did something similar. It needs to be sync'ed with master.

**Comment by fbemm** [comment]
What is the current preset / parameter set for mapping contigs against a graph?

**Comment by jeizenga** [comment]
The codebase has diverged quite a bit since this PR and something similar now exists in both map and mpmap. Some of the presets might still be worthwhile additions, but I think it would be as easy to start this PR over again as to sync it up.

**Pull request closed without merging**
