### PR TITLE
Add is_reversed option into target_alignment

### PR DESCRIPTION
**Pull request by 6br**
Refer: #1544 
Now vg annotate accepts BED format with strands(+/-) -- gene/exon annotations include the direction of strands, which should not discard.

### CODE REVIEW

**Comment by adamnovak** [comment]
This looks OK to test on Jenkins.

But it also looks like you didn't add the new bool parameter in xg.cpp, so it doesn't actually build. I guess you didn't commit that file?

**Comment by 6br** [comment]
Yes, I have comitted `xg.hpp`.

**Comment by 6br** [comment]
Now it accepts the BED format like below.

```
x      13        17      gene	0	-   # -> BACKWARD
x      13        17      gene               # -> default(FORWARD)
x      13        17      gene	0	+  # -> FORWARD
```

**Comment by 6br** [comment]
I think it is OK to test on Jenkins.

**Comment by adamnovak** [comment]
Jenkins test this please

**Comment by adamnovak** [comment]
Jenkins test this please.

**Comment by 6br** [comment]
It is ready to be merged.

**Pull request merged**
