### PR TITLE
Remove fun

### PR DESCRIPTION
**Pull request by adamnovak**
This reverts commit 36d47dfb3872a16c554b5eed828a642a804871d4.

### CODE REVIEW

**Comment by jeizenga** [comment]
WHYYYYYYY

**Comment by jeizenga** [comment]
Y'know I could just close the PR... 😏😏😏😏😏😏😏😏

**Comment by ekg** [comment]
It's ok. I've begun work on gyeet for all your yeeting needs.

**Comment by jeizenga** [comment]
Booooooooooo

**Pull request merged**
