### PR TITLE
Rdf build ♥

### PR DESCRIPTION
**Pull request by ekg**
c'mon travis!

I changed the deps and make sure the raptor build was pushing its files to the right place in the includes directory.

### CODE REVIEW

**Comment by ekg** [comment]
Will resolve #252

**Comment by ekg** [comment]
This build now works for Linux but fails on OSX due to a bison dependency issue.

```
CMake Error at /usr/local/Cellar/cmake/3.0.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find BISON: Found unsuitable version "2.3", but required is at
  least "3" (found /usr/bin/bison)
```

**Comment by ekg** [comment]
I don't get the failure. brew suggests that Bison 3.04 is installed: http://braumeister.org/formula/bison

Could someone with access to brew please check what's up?

**Comment by pgrosu** [comment]
It's installed in two locations:

/usr/local/Cellar/bison/3.0.4

/usr/bin/bison (which is 2.3)

You can either run it with `brew link bison --force` or might just need to update the $PATH to read `/usr/local/bin` before `/usr/bin`, as noted at the following link:

http://stackoverflow.com/questions/24835116/bison-latest-version-installed-but-not-in-use

Hope it helps,
~p

**Comment by ekg** [comment]
I've got this far:

```
g++ -O3 -msse4.1 -fopenmp -std=c++11 -ggdb -o bin/vg obj/main.o obj/gssw_aligner.o obj/vg.o cpp/vg.pb.o obj/index.o obj/mapper.o obj/region.o obj/progress_bar.o obj/vg_set.o obj/utility.o obj/path.o obj/alignment.o obj/edit.o obj/sha1.o obj/json2pb.o obj/entropy.o obj/pileup.o obj/caller.o obj/position.o obj/deconstructor.o -static -static-libstdc++ -static-libgcc -I/Users/travis/build/vgteam/vg/include -I. -I/Users/travis/build/vgteam/vg/src -I/Users/travis/build/vgteam/vg/cpp -I/Users/travis/build/vgteam/vg/include/dynamic -ggdb -L/Users/travis/build/vgteam/vg/lib -lvcflib -lgssw -lprotobuf -lhts -lpthread -ljansson -lncurses -lrocksdb -lsnappy -lz -lbz2 -lgcsa2 -lxg -lsdsl -ldivsufsort -ldivsufsort64 -lvcfh -lgfakluge -lraptor2 -L/usr/local/lib
ld: library not found for -lcrt0.o
collect2: error: ld returned 1 exit status
make: *** [static] Error 1
```

My inclination is to avoid the static OSX build. Questions abound already: Where is libcrt0 coming into this?

**Comment by ekg** [comment]
Thanks @pgrosu that bit fixed the bison problem!

The last part is just to avoid testing the static build on OSX. If you or anyone would like to make static OSX builds work, please see what you can do! It claims to be missing libcrt0. Typically this means we'll need to add it as -lcrt0 or such. Fixing this in the `-static` build may lead to another dependency, and so on. I don't now how deep down the rabbit hole we've gone.

**Comment by ekg** [comment]
(Reset the PR to try to convince travis to run the OSX build.)

**Comment by pgrosu** [comment]
@ekg Sorry to reply so late to this as it's been a bit busy lately, and I wanted to think a bit more of the possibilities.  So the easiest one without chaning internally on the gcc code and recompiling it, would be to perform the following based on http://stackoverflow.com/questions/5259249/creating-static-mac-os-x-c-build.  Below is the full example that shows how to build in the library on a Mac statically:

```Bash
$ cat example.h
void aFunction( int a );
$
$ cat example.c
#include <stdio.h>

void aFunction( int a )
{
    printf( "%d\n", a );
}
$
$ cat main.c
#include "example.h"

int main( ) 
{
    aFunction( 3 );

    return 0;
}
$
$ gcc -c example.c
$
$ ar -r libmylibrary.a  example.o
ar: creating archive libmylibrary.a
$
$ gcc main.c -lmylibrary -L. -I. -o main
$
$ ./main 
3
$
```

Then by inspecting the library, we see the function:

```Bash
$ nm libmylibrary.a 

libmylibrary.a(example.o):
0000000000000000 T _aFunction
                 U _printf

$ 
```

Then by inspecting the `main` program we see that the library is embedded:

```Bash
$ nm main
0000000100000000 T __mh_execute_header
0000000100000f60 T _aFunction
0000000100000f30 T _main
                 U _printf
                 U dyld_stub_binder
$
```
When we inspect it's dependencies, there are no dependencies other than the system library that is core for the Mac:

```Bash
$ otool -L main
main:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

Hope it helps,
~p

**Pull request merged**
