### PR TITLE
Use a trivial paired-end mapper

### PR DESCRIPTION
**Pull request by adamnovak**
This will let us get Jenkins results that at least get as high precision
as the single-end mapper.

### CODE REVIEW

**Comment by ekg** [comment]
Is there any reason not to merge this?

**Comment by ekg** [comment]
Oh, is this something we can enable via a command line flag?

**Comment by adamnovak** [comment]
This should not be merged really, because it hardcodes the mapper to this trivial implementation.

I'm concerned that this passes the tests, because that indicates that our tests are not very stringent. But there's also a question of why this does even vaguely well.

**Comment by adamnovak** [comment]
OK it turns out that I hadn't hit all the calls to the old mapper, so the old mapper was still running.

*Now* this should actually be running the mapper I want it to.

**Comment by adamnovak** [comment]
The trivial test mapper now matches the single-end mapper exactly. There's nothing weird going on here anymore.

**Pull request closed without merging**
