### PR TITLE
Cleaned up protobuf datamodel comments and (meta)data

### PR DESCRIPTION
**Pull request by macieksmuga**

### CODE REVIEW

**Comment by macieksmuga** [comment]
related to https://github.com/vgteam/xg/pull/16

**Comment by ekg** [comment]
Oh this is a nice one. We should pick it back up. The failure was dependency related?

**Comment by ekg** [comment]
@macieksmuga I did some of this but what's missing are the comments that you added (I removed metadata and data fields). Would you please check to see if you can add your comments back in?

**Comment by ekg** [comment]
@macieksmuga did you want to update the comments? If not I'll close this.

**Comment by ekg** [comment]
This is roughly matched by master.

**Pull request closed without merging**
