### PR TITLE
Handle-ify SLLS

### PR DESCRIPTION
**Pull request by adamnovak**
This builds on #2376 and fixes the build system to fully rebuild libbdsg when the libhandlegraph headers change. This ought to pass CI.

### CODE REVIEW

**Comment by adamnovak** [comment]
@jeizenga I think your changes have upset the tube map on its default example:

```
vg chunk err data: warning:[XG] Loading an out-of-date XG format. In-memory conversion between versions can be time-consuming. For better performance over repeated loads, consider recreating this XG with 'vg index' or upgrading it with 'vg xg'.
vg chunk err data: 

vg chunk err data: Crash report for vg v1.17.0-257-g3c66c50b7 "Candida"

vg chunk err data: Stack trace (most recent call last):

vg chunk err data: #
vg chunk err data: 9    Object "", at 0xffffffffffffffff, in 

vg chunk err data: #8    Object "/public/home/anovak/build/vg/bin/vg", at 0x961add, in _start

vg chunk err data: #7    Object "/usr/lib64/libc-2.17.so", at 0x7f9cc17cc444, in __libc_start_main

vg chunk err data: #6    Object "/public/home/anovak/build/vg/bin/vg", at 0x8a4fde, in main
      Source "src/main.cpp", line 73, in main [
vg chunk err data: 0x8a4fde]

vg chunk err data: #5    Object "/public/home/anovak/build/vg/bin/vg", at 0xda42f7, in vg::subcommand::Subcommand::operator()(int, char**) const
    | Source "src/subcommand/subcommand.cpp", line 72, in operator()

vg chunk err data:       Source "/public/home/anovak/.local/include/c++/8.1.0/bits/std_function.h", line 687, in operator() [0xda42f7]

vg chunk err data:         684:     {
        685:       if (_M_empty())
       
vg chunk err data:  686: 	__throw_bad_function_call();
      > 687:       return _M_invoker(_M_functor, std::forward<_ArgTypes>(__args)...);
        688:     }
        689: 
        690: #if __cpp_rtti

vg chunk err data: #4    Object "/public/home/anovak/build/vg/bin/vg", at 0xdde9d6, in main_chunk(int, char**)
      Source "src/subcommand/chunk_main.cpp", line 499, in main_chunk [0xdde9d6]

vg chunk err data: #3    Object "/public/home/anovak/.local/lib/libgomp.so.1.0.0", at 0x7f9cc1d9c97e, in GOMP_parallel
      Source "
vg chunk err data: /public/home/anovak/build/gcc-8.1.0/libgomp/parallel.c", line 168, in GOMP_parallel [0x7f9cc1d9c97e]

vg chunk err data: #2    Object "/public/home/anovak/build/vg/bin/vg", at 0xddb92d, in main_chunk(int, char**) [clone ._omp_fn.0]
      Source "src/subcommand/chunk_main.cpp", line 539, in _Z10main_chunkiPPc._omp_fn.0 [0xddb92d]
vg chunk err data: 

vg chunk err data: #1    Object "/public/home/anovak/build/vg/bin/vg", at 0xe1bc5d, in vg::trace_haplotypes_and_paths(handlegraph::PathHandleGraph const&, gbwt::GBWT const&, long, int, vg::Graph&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >&, bool)
      Source "src/haplotype_extracter.cpp", line 18, in trace_haplotypes_and_paths [0xe1bc5d]

vg chunk err data: #0    Object "/public/home/anovak/build/vg/bin/vg", at 0xe1af92, in vg::list_haplotypes(handlegraph::HandleGraph const&, gbwt::GBWT const&, unsigned long, int)
    | Source "src/haplotype_extracter.cpp", line 177, in find

vg chunk err data:     | Source "/public/home/anovak/build/vg/include/gbwt/gbwt.h", line 108, in find<gbwt::GBWT>

vg chunk err data:     |   106:   */
    |  
vg chunk err data:  107: 
    | > 108:   SearchState find(node_type node) const { return gbwt::find(*this, node); }
    |   109: 
    |   110:   template<class Iterator>
    | Source "/public/home/anovak/build/vg/include/gbwt/algorithms.h", line 117, in contains
    |   115: find(const GBWTType& index, node_type node)
    |   116: {
    | > 117:   if(!(index.contains(node))) { return SearchState(); }
    |   118:   return SearchState(node, 0, index.nodeSize(node) - 1);
    |   119: 
vg chunk err data: }
      Source "/public/home/anovak/build/vg/include/gbwt/gbwt.h", line 155, in list_haplotypes [0xe1af92]
        153:   bool contains(node_type node) const
        154:   {
      > 155:     return ((node < this->sigma() && node > this->header.offset) || node == ENDMARKER);
        156:   }
        157: 
        158:   bool contains(edge_type position) const

vg chunk exited with code 139
```

Can you test the tube map with this branch?

**Comment by jeizenga** [comment]
Ah butts. Where'd this test output come from?

**Comment by adamnovak** [comment]
This came from the tube map console from `npm run serve`, when I went to the tube map homepage. I think it is working on the default example graph, snp1kg BRCA1, in here: https://github.com/vgteam/sequenceTubeMap/tree/master/exampleData

**Comment by adamnovak** [comment]
The tube map problem is that we try to trace haplotypes in the non-loaded GBWT if `-T` is passed to vg chunk, since the gPBWT code is now gone.

**Pull request merged**
