### PR TITLE
Groundwork for DP-based genotyper

### PR DESCRIPTION
**Pull request by adamnovak**
This sets up `Genotyper` to pass around `SnarlTraversal`s, although it still assumes all the `Visit`s are to nodes.

I'm also renaming the `visits` field on the `SnarlTraversal` protobuf, since they should be singular. I want to get this in before I write the real refactor.

### CODE REVIEW

**Comment by adamnovak** [comment]
The problem we're having now is that the genotyper, with the more complex augmented graph, is taking more memory than the Jenkins node has. I think that this is because embedding all the reads in the graph is very expensive. I'm going to try and tweak it so that it doesn't do that.

**Comment by glennhickey** [comment]
From what I was seeing before, it's the augmentation process itself (ie
edit()) that is the bottleneck.

**Comment by adamnovak** [comment]
I thought so too, but these tests definitely are logging failures during genotype.

**Comment by adamnovak** [comment]
We're passing the tests and increasing the Genotype F1s. Time to merge!

**Pull request merged**
