### PR TITLE
Changes to Snarl and SnarlTraversal standards

### PR DESCRIPTION
**Pull request by jeizenga**
I figured out SnarlTraversals need to have the boundary node walks included since they can be cyclic (i.e. it's not implicit). I've changed the .proto to reflect the new standard. I also have some infrastructural changes to go along with this update
- It's no longer necessary to store the Snarl inside a SnarlTraversal since it can be determined by looking at the nodes on either end of the traversal
- Added an index to get from a boundary Visit to a Snarl in the SnarlManager
- Removed the redundant child boundary indexes from SnarlManager

I also edited other people's code to be compliant to the new standard as far as I can tell. However, there was a lot of code that handled SnarlTraversals, so it would be smart to double check me. @edawson @adamnovak

### CODE REVIEW

**Comment by glennhickey** [comment]
Jenkins, test this please.

**Comment by glennhickey** [comment]
ok to test

**Comment by glennhickey** [comment]
@jeizenga If you click through the first failed Jenkins test you should get here:
http://jenkins.cgcloud.info/job/vg/50/testReport/junit/jenkins.vgci/VGCITest/test_full_brca2_cactus/

then if you squint at the stderr log long enough you should see this:

INFO:toil.lib.docker:Calling docker with ['docker', 'run', '--rm', '--log-driver', 'none', '--entrypoint', 'vg', '--env', 'TMPDIR=.', '-v', '/mnt/ephemeral/tmp/toil-dae8f372-b454-4892-8561-ac5cc00766b0/tmpoMk5YN/4a484572-c6df-4b81-9058-d943fc8ba48e/t7CRlHF:/data', '-w', '/data', 'jenkins-docker-vg-local', 'call', 'chunk_13_0.vg', 'chunk_13_0.pu', '-t', '8', '-S', 'NA12878', '-r', '13', '-c', '13', '-l', '84989', '-o', '32314860']
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 3) >= this->size() (which is 3)
ERROR:root:Failed. Dumping files.

which is basically vg call frowning on your new snarl shenanigans.  

you ought to be able to reproduce sans toil-vg by running pileup and call with some of the data mirrored here /hive/users/hickey/bakeoff-store/.  Let me know if you need help.

**Comment by jeizenga** [comment]
I can't get to the logs. They seem to have gone down for some reason. Any idea what's going on there?

**Comment by glennhickey** [comment]
Seems ok here.

Can you get anywhere from here?  (It asks me to clock something to log in
via github then works fine).

I suspect there's something in the general Jenkins setup (which I don't
have privilge to see) that may be limiting all access to people in the
bd2kgenomics group (which you should be a member of btw).

**Comment by glennhickey** [comment]
Meant to include http://jenkins.cgcloud.info/ after that question

**Comment by jeizenga** [comment]
Hmm. I can't follow that link either. Just get this.

screen shot 2017-06-07 at 10 48 33 am

**Comment by adamnovak** [comment]
Not coincidentally, the domain was updated yesterday, on the anniversary of
its registration.

anovak@hex:~$ whois cgcloud.info
Domain Name: CGCLOUD.INFO
Registry Domain ID: D55199025-LRMS
Registrar WHOIS Server:
Registrar URL: http://www.gandi.net
Updated Date: 2017-06-06T22:22:30Z
Creation Date: 2015-06-06T21:37:23Z
Registry Expiry Date: 2018-06-06T21:37:23Z
...

I suspect Glenn has the DNS cached. All of cgcloud.info NXDOMAINs for me.
Maybe someone forgot to renew it.

**Comment by jeizenga** [comment]
Who do I shake a fist at?

**Comment by glennhickey** [comment]
It's apparently being dealt with.  In the meantime, this should work

http://jenkins-balancer-1572100883.us-west-2.elb.amazonaws.com/

**Comment by jeizenga** [comment]
@glennhickey Where are the reads that this test failed on? All I see in that hive directory are graphs and indexes.

**Comment by glennhickey** [comment]
Everything's in the directory.

ls -l /hive/users/hickey/bakeoff-store/platinum_NA12878_BRCA2.fq.gz
-rw-r--r-- 1 hickey protein 1175066 Apr  4 11:02 /hive/users/hickey/bakeoff-store/platinum_NA12878_BRCA2.fq.gz

**Comment by jeizenga** [comment]
I just ran the following commands for every graph/read combo in that directory:

```vg map -x XG -g GCSA -A -f FASTQ > GAM
vg pileup VG GAM > PILEUP
vg call VG PILEUP > /dev/null
```

But I didn't get any crash. Am I doing something differently than Jenkins is?

**Comment by glennhickey** [comment]
Probably.  In theory the intermediate files should be available on Jenkins,
but I see I still haven't fixed them to be public since the account got
moved.

I'm building your branch now, and will try to reproduce here.

**Comment by glennhickey** [comment]
Here you go:

/hive/users/hickey/jordan/test-bakeoff-out-store-brca1-snp1kg/

See /hive/users/hickey/jordan/test-bakeoff-out-store-brca1-snp1kg/README
for command line to reproduce

**Comment by jeizenga** [comment]
I just had an idea. This might be due to the Makefile bug in https://github.com/vgteam/vg/issues/680. Could you try running make twice on my branch and then see if you can still reproduce?

**Comment by glennhickey** [comment]
The Jenkins link should work now FWIW.  I just checked and all the calling tests are failing.  About half run without crashing but reduce F1 significantly.  The other half all die with something like

what():  Couldn't find 10313 fwd-10315 fwd fwd in backbone path of site 10310 fwd to 10313 fwd

**Comment by jeizenga** [comment]
Good call on the old .xg files, I can get map to run now. Unfortunately, still having problems replicating the bug. It runs without issue for me locally. How do those chunks get made? Maybe if I make those I can reproduce.

**Comment by jeizenga** [comment]
I did it! Also, it looks like the F1 scores... increased? I don't know what I did to make that happen, but you're welcome. Merge please?

**Comment by glennhickey** [comment]
You're not kidding!  Must have been all the extra care I took while emailing you the example files.

**Pull request merged**
