### PR TITLE
VG inject command -- the conversion from bam to gam format

### PR DESCRIPTION
**Pull request by 6br**
Refer: #1561 

Whether the inject command is well-implemented can be tested by *the surjection of the injection* of the alignments for the linear reference.

TODO LIST

- [x] Add tests
- [x] Add `inject` subcommand interface
- [x] Add `cigar_mapping`, `mapping_against_path` function, which are the dual functions of `mapping_cigar` and `cigar_against_path`.
- [x] Modify `map_alignment` function to accept cigars.
- [x] Debug
- [x] Remove unused functions, Refactoring

### CODE REVIEW

**Comment by adamnovak** [comment]
Jenkins, OK to test.

**Comment by 6br** [comment]
For now, only BAM is accepted, but SAM and CRAM will be supported soon.

**Comment by 6br** [comment]
My plan:
* First, convert CIGARs of BAM into the ordered set of Edit
    * to determine the end position of alignments
* Second, add a new function based `target_alignment` with consuming Edits
* Finally, integrate into map_alignment function

**Comment by 6br** [comment]
How to handle clips or some corner cases will follow the implementation of `vg surject`.

**Comment by ekg** [comment]
@6br note that we've just changed the default surjection algorithm. Please ping @jeizenga if you'd like to discuss details and how they might relate to inject.

**Comment by 6br** [comment]
@jeizenga  Could you tell me the overview of new `vg surject` or suggestions for `vg inject`? 
Is there already useful APIs for the injection?

**Comment by jeizenga** [comment]
I have a high-level overview of the algorithm in the issue where I originally proposed it: https://github.com/vgteam/vg/issues/1470. It's implemented pretty faithfully to that plan. The code of the main algorithm is here: https://github.com/vgteam/vg/blob/master/src/surjector.cpp#L409.

**Comment by 6br** [comment]
Thank you.

At first, I will not do realignment for the graph to keep the consistency between edits and CIGARs.

**Comment by 6br** [comment]
All tests have passed. Can anyone review my code?

**Comment by ekg** [comment]
It looks great to me! Thank you for an awesome new tool!

**Pull request merged**
