### PR TITLE
Subgraph extraction algorithm for read tails

### PR DESCRIPTION
**Pull request by jeizenga**
Adds another subgraph extraction algorithm designed for read tails as well as tests.

### CODE REVIEW

**Comment by jeizenga** [comment]
@glennhickey I think some change to the caller found it's way in here when I was trying to fix up my git state (oops). Does this look right to you?

**Comment by glennhickey** [comment]
I don't know what you've done to git, but those "changes" in caller seem to jive with what's in master now.

**Comment by jeizenga** [comment]
Can we merge it without disrupting the space time continuum?

**Comment by glennhickey** [comment]
Probably.  Make sure to turn off your hadron collider first just in case.

**Comment by jeizenga** [comment]
Can I get a merge on this?

**Comment by jeizenga** [comment]
Oh wait, I just noticed that some extra files made it into this commit. Hold off a sec.

**Comment by jeizenga** [comment]
Oh wait, nvm false alarm. Merge me plz.

**Pull request merged**
