### PR TITLE
Update to and synchronize latest libhandlegraph and related dependencies

### PR DESCRIPTION
**Pull request by adamnovak**
This replaces #2561 by bumping libbdsg to the latest version.

### CODE REVIEW

**Comment by mr-c** [comment]
Thanks!

**Comment by mr-c** [comment]
```
In file included from src/hash_graph.cpp:5:0:

include/bdsg/hash_graph.hpp:12:10: fatal error: handlegraph/serializable_handle_graph.hpp: No such file or directory

 #include <handlegraph/serializable_handle_graph.hpp>

          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by adamnovak** [comment]
It turns out we need to adapt a bunch of our other libraries to other libhandlegraph changes made in the latest version.

In particular this PR can't test properly until @jltsiren merges https://github.com/jltsiren/gbwtgraph/pull/4

**Comment by jeizenga** [comment]
Is this ready for a merge?

**Comment by adamnovak** [comment]
Yep!

**Pull request merged**
