### PR TITLE
Improve human paired end performance

### PR DESCRIPTION
**Pull request by ekg**
That's the goal of this PR. It's not good at present. The first thing I'll check is if running the clustering in "regular" mode (rather than the weird "paired" mode) improves our performance.

### CODE REVIEW

**Comment by adamnovak** [comment]
Looks like vg map segfaulted (exit 139 = -11)?

**Comment by glennhickey** [comment]
E           vg: src/cluster.cpp:1379: vg::Graph vg::cluster_subgraph(const
xg::XG&, const vg::Alignment&, const std::vector<vg::MaximalExactMatch>&,
double): Assertion `mems.size()' failed.

**Comment by adamnovak** [comment]
That's the mpmap test; I was looking at the normal mapper test.

**Comment by adamnovak** [comment]
OK, I've pushed my own commit that seems to make the mapper not crash by keeping some vectors in sync. We'll see how Jenkins likes that.

**Comment by ekg** [comment]
Thanks @adamnovak I caught the segfault at the end of yesterday's workday but hadn't patched it!

**Comment by adamnovak** [comment]
Since this does look like it's more or less an improvement, and since it includes some bugfixes, should we merge this?

**Comment by adamnovak** [comment]
I've restarted Mac Travis; it ran out of time building rocksdb.

**Comment by ekg** [comment]
@adamnovak I'm not yet ready to merge, but I've tried to sync with master. Seems like the rocksdb index change has caused some problems for me. Now I'm getting an error in the build where it's looking for `-ltbb` or libtbb. That's getting pulled in from rocksdb now. I'm trying to hack it out and see if I can still pass the tests. (I do compile, so maybe that's enough to ensure it's the right thing.)

**Comment by ekg** [comment]
Things are improving but I'm still stuck on a particular error mode that's very annoying. See the pseudo-ROC.

hg002 1m wg 6-results-f33f073 roc

The sensitivity is getting to where it should be, but a serious false positive rate problem remains.

This is the debug log from aligning the failing reads for the reference-only vg mapping. At least one member in each pair is failing and they have above mapping quality 50.

[vg-ref-pe.fail.v1.5.0-1328-gf33f073.gam.err.1.txt](https://github.com/vgteam/vg/files/1333971/vg-ref-pe.fail.v1.5.0-1328-gf33f073.gam.err.1.txt)

There are a two things that seem to be happening a lot in this set of reads.

1. One read in the pair is at such high abundance that it gets no or very few MEMs--- the rest are filtered out because they are too high in abundance. This presumably could/should be tracked and incorporated into the mapping quality estimate.

2. Only a single proper pair is found, and it happens to be the wrong one. Finding a single proper pair isn't so bad... but it could be a problem if we expect a lot of hits for both of the reads in the pair. I'm not sure how to deal with this but it is certain that it totally violates the assumptions in the mapping quality calculation. I'm not getting good results flipping the calc back to single-ended in the case that we don't have more than one proper pair.

**Comment by adamnovak** [comment]
We definitely would want to distinguish between searches that fail due to
having too many hits and those that fail due to having too few.

When we find only one pair, maybe we want to use arbitrary pairings-up of
the other hits as the mapping quality secondaries?

**Comment by ekg** [comment]
@glennhickey is there a mapping quality threshold in vg call that might be getting tripped up in this one test?

**Comment by glennhickey** [comment]
Yeah, it's dropping anything below mapq 15.

It looks like this PR is causing two BRCA1 calls that were previously
correct to now get the wrong zygosity.  The quality or some other arbitrary
threshold could very well be at play, so I wouldn't worry much about it if
everything else is looking good.

**Comment by ekg** [comment]
That's a decently high threshold. I'll try dropping it to 1 to see if this makes Jenkins happy.

**Comment by ekg** [comment]
@glennhickey where is the threshold set? I'm having some trouble finding it.

**Comment by ekg** [comment]
Here's a pseduo-ROC for human using the settings for 2cde059:

image

Increasing the maximum hit count really helps us, and increasing the min MEM length doesn't hurt much but really improves speed.

The good news is that, provided we can work through problems in the CI with other regions, it looks like the objective of this PR has been reached. We can now exceed the AUC of bwa mem on human. The only thing that we need to decide is where we want to sit on the alignment speed / accuracy tradeoff.

**Comment by glennhickey** [comment]
Don't listen to your bones -- the juice is clearly working.

On the Jenkins chrom 21 test, you can even see the threshold graph beating
bwa mem in some respects (accuracy and max f1), which I think is a first
for this test.  Would be interesting to see the results on Jordan's
simulator -- I'll set up a PR to test this.  I'd also like to rerun the old
"test_map_mhc_snp1kg" to double check regressions in the caller.

**Comment by ekg** [comment]
Is Jordan running his simulator off of recalibrated BAMs? I'd be curious what that would do. Worried about low error rates being a result of overconfidence in the Qs.

**Comment by glennhickey** [comment]
The platinum genomes bams are apparently recalibrated -- just that they're
only 101 bp.  We've still been scaling up the error rate to get the total
to be consistent with your numbers.    But even with the same overall error
rate (and fragment and read lengths and indel proportion), we're seeing a
difference on the curves when switching between the uniform errors and the
base-qualitiy-based errors.     Jordan speculates that pushing the errors
towards the ends of the reads lets us expect longer mems.

**Comment by glennhickey** [comment]
test_map_mhc_primary is crashing now

NFO:toil.lib.docker:Calling docker with ['docker', 'run', '--rm',
'--log-driver', 'none', '--entrypoint', 'vg', '--env', 'TMPDIR=.', '--env',
'LC_ALL=C', '-v', '/mnt/ephemeral/tmp/toil-366d90d1-098a-4993-9f0d-
9508c5e5dfa8-dd1bac9cb23792a632bd6ee157719517/tmpD_ALZm/0e7b772f-e38f-
4613-b57e-9689ec384f80/twgB2Ub:/data', '-w', '/data', '--name',
u'runchunkalignment--43IASd6FbyTi', 'jenkins-docker-vg-local', 'map', '-f',
'reads_chunk_0_0.fq.gz', '-t', '8', '-i', '-x', 'graph.vg.xg', '-g',
'graph.vg.gcsa']
*vg: src/mapper.cpp:1782: bool vg::Mapper::pair_consistent(**const
vg::Alignment&, const vg::Alignment&, double): Assertion
`aln1.fragment_size() == aln2.fragment_size()' failed.*

test_sim_chr21_snp1kg seems to have died at the R plotting step.  Not sure
why by looking at the logs.

**Comment by glennhickey** [comment]
@ekg For the brca1 test, it does seem to be due to false positives linked
to increasing mapping qualities.

Here's s pair that has quality 47/48 on this branch but has only one side
align with quality 16 on master.   I can drum up some more if that's
useful...

Mapper branch:

{"sequence":
"TATATATAACATATTATATATAACATATGTATGTTATATATATATAACATATTATATATAACATATGTATGTTATATATATATAACATATTATATATAACA",
"fragment_length_distribution": "931:213.273:71.8518:0:1", "path":
{"mapping": [{"edit": [{"from_length": 10, "to_length": 10}], "position":
{"node_id": 5200, "offset": 1}, "rank": 1}, {"edit": [{"from_length": 2,
"to_length": 2}], "position": {"node_id": 5201}, "rank": 2}, {"edit":
[{"from_length": 1, "to_length": 1}, {"to_length": 1, "sequence": "T"},
{"from_length": 14, "to_length": 14}, {"from_length": 1, "to_length": 1,
"sequence": "G"}, {"from_length": 3, "to_length": 3}], "position":
{"node_id": 5202}, "rank": 3}, {"edit": [{"from_length": 1, "to_length":
1}], "position": {"node_id": 5203}, "rank": 4}, {"edit": [{"from_length":
1, "to_length": 1}], "position": {"node_id": 5206}, "rank": 5}, {"edit":
[{"from_length": 1, "to_length": 1}], "position": {"node_id": 5208},
"rank": 6}, {"edit": [{"from_length": 16, "to_length": 16}, {"to_length":
1, "sequence": "T"}, {"from_length": 5, "to_length": 5}], "position":
{"node_id": 5209}, "rank": 7}, {"edit": [{"from_length": 2, "to_length":
2}, {"to_length": 3, "sequence": "AAC"}, {"from_length": 4, "to_length":
4}, {"from_length": 1, "to_length": 1, "sequence": "G"}, {"from_length":
20, "to_length": 20}, {"to_length": 3, "sequence": "TAT"}, {"from_length":
5, "to_length": 5}], "position": {"node_id": 5211}, "rank": 8}, {"edit":
[{"from_length": 1, "to_length": 1}], "position": {"node_id": 5212},
"rank": 9}, {"edit": [{"from_length": 1, "to_length": 1}], "position":
{"node_id": 5214}, "rank": 10}, {"edit": [{"from_length": 4, "to_length":
4}], "position": {"node_id": 5215}, "rank": 11}]}, "fragment_next":
{"name": "ERR194147.785083497/2"}, "name": "ERR194147.785083497/1",
"quality":
"GxsbGyEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEbISEhISEhISEhISEhISEhISEhISEhISEhIRshGxshGyEhISEhGyEbGxYWDw8PDw8PDw8PGyE=",
"score": 65, "identity": 0.90099009900990101, "refpos": [{"offset": 56275,
"name": "17"}], "mapping_quality": 47, "fragment": [{"name": "17"}],
"secondary_score": [39, 0]}
{"sequence":
"ATATGTTATATATAATATGTTATATATATATAACATACATATGTTATATATAATATGTTATATATATATAACATACATATGTTATATATAATATGTTATAT",
"fragment_length_distribution": "931:213.273:71.8518:0:1", "path":
{"mapping": [{"edit": [{"from_length": 7, "to_length": 7}], "position":
{"node_id": 5215, "is_reverse": true, "offset": 10}, "rank": 1}, {"edit":
[{"from_length": 1, "to_length": 1}], "position": {"node_id": 5214,
"is_reverse": true}, "rank": 2}, {"edit": [{"from_length": 1, "to_length":
1}], "position": {"node_id": 5212, "is_reverse": true}, "rank": 3},
{"edit": [{"from_length": 5, "to_length": 5}, {"to_length": 3, "sequence":
"ATA"}, {"from_length": 20, "to_length": 20}, {"from_length": 1,
"to_length": 1, "sequence": "C"}, {"from_length": 4, "to_length": 4},
{"to_length": 3, "sequence": "GTT"}, {"from_length": 2, "to_length": 2}],
"position": {"node_id": 5211, "is_reverse": true}, "rank": 4}, {"edit":
[{"from_length": 5, "to_length": 5}, {"to_length": 1, "sequence": "A"},
{"from_length": 16, "to_length": 16}], "position": {"node_id": 5209,
"is_reverse": true}, "rank": 5}, {"edit": [{"from_length": 1, "to_length":
1}], "position": {"node_id": 5208, "is_reverse": true}, "rank": 6},
{"edit": [{"from_length": 1, "to_length": 1}], "position": {"node_id":
5206, "is_reverse": true}, "rank": 7}, {"edit": [{"from_length": 1,
"to_length": 1}], "position": {"node_id": 5203, "is_reverse": true},
"rank": 8}, {"edit": [{"from_length": 3, "to_length": 3}, {"from_length":
1, "to_length": 1, "sequence": "C"}, {"from_length": 14, "to_length": 14},
{"to_length": 1, "sequence": "A"}, {"from_length": 1, "to_length": 1}],
"position": {"node_id": 5202, "is_reverse": true}, "rank": 9}, {"edit":
[{"from_length": 2, "to_length": 2}], "position": {"node_id": 5201,
"is_reverse": true}, "rank": 10}, {"edit": [{"from_length": 7, "to_length":
7}], "position": {"node_id": 5200, "is_reverse": true}, "rank": 11}]},
"fragment_prev": {"name": "ERR194147.785083497/1"}, "name":
"ERR194147.785083497/2", "quality":
"IRsbGyEhISEhISEbISEhISEbISEhISEhISEhISEhISEhGyEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEbISEbGyEbGxsbGxsbGxYWIRYbDw8PDw8PDw8PDw8=",
"score": 65, "identity": 0.90099009900990101, "refpos": [{"offset": 56275,
"name": "17"}], "mapping_quality": 48, "fragment": [{"name": "17"}],
"secondary_score": [38, 0]}

master

{"secondary_score": [57, 44, 38, 21, 19, 13], "sequence":
"ATATGTTATATATAATATGTTATATATATATAACATACATATGTTATATATAATATGTTATATATATATAACATACATATGTTATATATAATATGTTATAT",
"path": {"mapping": [{"edit": [{"from_length": 7, "to_length": 7}],
"position": {"node_id": 5215, "offset": 10, "is_reverse": true}, "rank":
1}, {"edit": [{"from_length": 1, "to_length": 1}], "position": {"node_id":
5214, "is_reverse": true}, "rank": 2}, {"edit": [{"from_length": 1,
"to_length": 1}], "position": {"node_id": 5212, "is_reverse": true},
"rank": 3}, {"edit": [{"from_length": 5, "to_length": 5}, {"to_length": 3,
"sequence": "ATA"}, {"from_length": 20, "to_length": 20}, {"sequence": "C",
"from_length": 1, "to_length": 1}, {"from_length": 4, "to_length": 4},
{"to_length": 3, "sequence": "GTT"}, {"from_length": 2, "to_length": 2}],
"position": {"node_id": 5211, "is_reverse": true}, "rank": 4}, {"edit":
[{"from_length": 5, "to_length": 5}, {"to_length": 1, "sequence": "A"},
{"from_length": 16, "to_length": 16}], "position": {"node_id": 5209,
"is_reverse": true}, "rank": 5}, {"edit": [{"from_length": 1, "to_length":
1}], "position": {"node_id": 5208, "is_reverse": true}, "rank": 6},
{"edit": [{"from_length": 1, "to_length": 1}], "position": {"node_id":
5206, "is_reverse": true}, "rank": 7}, {"edit": [{"from_length": 1,
"to_length": 1}], "position": {"node_id": 5203, "is_reverse": true},
"rank": 8}, {"edit": [{"from_length": 3, "to_length": 3}, {"sequence": "C",
"from_length": 1, "to_length": 1}, {"from_length": 14, "to_length": 14},
{"to_length": 1, "sequence": "A"}, {"from_length": 1, "to_length": 1}],
"position": {"node_id": 5202, "is_reverse": true}, "rank": 9}, {"edit":
[{"from_length": 2, "to_length": 2}], "position": {"node_id": 5201,
"is_reverse": true}, "rank": 10}, {"edit": [{"from_length": 7, "to_length":
7}], "position": {"node_id": 5200, "is_reverse": true}, "rank": 11}]},
"name": "ERR194147.785083497/2", "mapping_quality": 16, "score": 65,
"quality":
"IRsbGyEhISEhISEbISEhISEbISEhISEhISEhISEhISEhGyEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEbISEbGyEbGxsbGxsbGxYWIRYbDw8PDw8PDw8PDw8=",
"identity": 0.90099009900990101, "refpos": [{"offset": 56275, "name":
"17"}]}

**Comment by ekg** [comment]
Am I reading this right that in this pair the reads are perfect reverse complements of each other? That's definitely a phenomenon that can happen in sequencing, and not something the simulator might do correctly. It means the base observations non-independent, so maybe the mq calculation should be handled differently.

On the other hand, it looks like we are just missing candidate alignments. I'll do a quick check to see if I can recover the Jenkins test performance by lowering the min MEM length, which I've jacked up pretty high. It could be causing the lack of sensitivity to the alternative alignments.

**Comment by ekg** [comment]
What's with the thresholds on the call runs? Are they programmatically generated?

**Comment by glennhickey** [comment]
The last change helped.  False positives down to 10.  The quality 15
threshold was tuned to the giab and platinum genomes benchmarks a while
back.  It didn't seem to have any bearing on the cases I was looking at
here.  In general, I'd love to get rid of it though.

I will look at some of the remaining false positives now.

I also want to reactivate the snp1kg-mhc calling test.  It doesn't even run
through now -- getting:

NFO:toil-rt:Run: vg map -f reads_chunk_0_0.fq.gz -t 8 -i -x graph.vg.xg -g
graph.vg.gcsa
vg: src/mapper.cpp:1782: bool vg::Mapper::pair_consistent(const
vg::Alignment&, const vg::Alignment&, double): Assertion
`aln1.fragment_size() == aln2.fra
gment_size()' failed.

**Comment by ekg** [comment]
Ah ok, sorry. Well it looks like the failures were caused by the too-short min MEM length. That's interesting. Unfortunate too, because that was a key to getting things to run faster. They're not as fast as we'd like them now...

**Comment by glennhickey** [comment]
The good news is that the test passed locally for me (though with a teeny
regression in F1) and there were no crashes.  So if you re-comment out
test_sim_mhc_snp1kg and rebase off of master, you should be good to go from
a CI point of view.

**Pull request merged**
