### PR TITLE
Fix new[]/delete mismatch

### PR DESCRIPTION
**Pull request by adamnovak**
This may or may not help with #1508.

If you make an array with new, you need to delete it with `delete[]`.

### CODE REVIEW

**Comment by adamnovak** [comment]
I'm actually pretty sure that this won't fix #1508; the problem was present in the last known good commit for that issue. But undefined behavior is undefined, which includes potentially changing in behavior for no apparent reason. So maybe this is somehow the cause anyway.

**Comment by ekg** [comment]
@adamnovak do you see a huge slowdown on your own system from this? Could Jenkins be sad because of competing processes on the same node?

**Comment by adamnovak** [comment]
@ekg Jenkins has been thrown out of whack because Edwin on our end changed the Jenkins worker image to one that uses the current version of Toil (because Jenkins updated and stopped running properly on the older images). We found that our tests didn't work right with current Toil as of a few months ago, but we just decided to use the old Toil indefinitely because we couldn't work out how to fix it.

I will have to see about getting Jenkins back in working order.

**Comment by adamnovak** [comment]
Jenkins has been fixed!

Jenkins, test this please.

**Pull request merged**
