### PR TITLE
synchronize deps/DYNAMIC

### PR DESCRIPTION
**Pull request by mr-c**
## Changelog Entry
To be copied to the [draft changelog](https://github.com/vgteam/vg/wiki/Draft-Changelog) by merger:

 * Updated to latest vgteam version of the DYNAMIC library

### CODE REVIEW

**Comment by mr-c** [comment]
This will help the next Debian release of vg as the updated submodule includes many patches we have submitted over the last year+

**Comment by adamnovak** [comment]
This failed the vg Gitlab build because of:

```
make: *** No rule to make target 'deps/DYNAMIC/include/*.hpp', needed by 'include/dynamic/dynamic.hpp'.  Stop.
make: *** Waiting for unfinished jobs....
```

I think we need to tell the vg Makefile that DYNAMIC has moved its headers into subdirectories.

**Comment by mr-c** [comment]
This looks ready to merge, thank you @adamnovak !

**Comment by adamnovak** [comment]
We never merged this because I never came back to kick the Travis Mac tests.

I've pulled in the current mainline vg so now it ought to pass all the tests and we can merge it.

**Comment by mr-c** [comment]
@adamnovak The CI was a success!

**Pull request merged**
