### PR TITLE
Cactus pair

### PR DESCRIPTION
**Pull request by ekg**
Getting pair rescue to work on complex graphs.

### CODE REVIEW

**Comment by ekg** [comment]
Jenkins, test this please.

**Comment by ekg** [comment]
@glennhickey any idea why Jenkins is failing here? Seems like it can't find blas?

**Comment by glennhickey** [comment]
Yeah, weird.  It's funny, because I was just running into the same thing
today on my own instance outside of Jenkins when trying to reproduce some
genome-wide stuff.

Somehow  (from jenkins/jenkins.sh)

# Upgrade pip so that it can use the wheels for numpy & scipy, so that they
# don't try to build from source
pip install --upgrade pip
pip install scipy

seems to have stopped working for us all of a sudden.  It looks like scipy
just got changed in pip today:

https://pypi.python.org/pypi/scipy/1.0.0

which is maybe related?  Since it seems to reproduce on nodes made from
toil launch-cluster, hopefully it won't be too long to debug.  @adamnovak
any ideas?

**Comment by glennhickey** [comment]
@ekg This looks like it's working:

https://github.com/vgteam/vg/pull/1198

**Comment by ekg** [comment]
Travis is just erroring out while generating the build script. What on earth...

**Pull request closed without merging**
