### PR TITLE
Vcf threads

### PR DESCRIPTION
**Pull request by adamnovak**
This can't merge yet (as I need to rebase), and I still want to revise the way the little allele paths are handled (to not put them in the XG index itself, because then it wastes loads of time making the tiny things into wavelet trees), but I figured I should open a PR for my better approach to loading phase threads from VCFs.

### CODE REVIEW

**Comment by ekg** [comment]
Any way I can help on this? I see you've integrated the callback based xg build, which is something I'm interested in using. I've run into some problems making the xg index for an MHC graph that I've generated (which is curious because the XG index is built internally in the process of long read assembly). I thought it would make sense to sync up with the current xg master, but it looks like you've already done all the integration here.

Is the blocking thing the allele paths?

**Comment by ekg** [comment]
I'm going to rebase, test, and likely merge. I need to keep up to pace with xg development because I'm trying to resolve #267 and some other issues. `XG::from_callback` might be the ticket.

It is OK in my mind if the feature does not scale yet. There is utility in keeping development together.

**Comment by edawson** [comment]
How should I zig with SuperBubbly then? Is it fine if it's on the latest XG?

**Comment by ekg** [comment]
If you can keep level with the master on this. We will update to use the
new xg in #272.

**Comment by ekg** [comment]
I've got the merge ready locally. I'm going to push it into master.

@adamnovak I don't see any tests handling the uses here. That's fine. We can add them when you're satisfied with the implementation.

Some things I'm interested in doing are adding an interface to read the paths file in for vg view (for debugging, coolness), and also a vg view option to dump the paths in json format.

**Pull request merged**
