### PR TITLE
A bit more handles

### PR DESCRIPTION
**Pull request by jeizenga**
Finished up some handlification I started yesterday

### CODE REVIEW

**Comment by glennhickey** [comment]
https://github.com/vgteam/vg/blob/master/src/subcommand/explode_main.cpp#L73-L76

**Comment by jeizenga** [comment]
Ah well, doesn't hurt, I guess.

**Comment by jeizenga** [comment]
@adamnovak I think Travis is acting up

**Comment by adamnovak** [comment]
It looks like Homebrew decided to remove the `brew bundle` and Brewfiles feature, so now when we try to do it it fails.

**Comment by adamnovak** [comment]
Actually, it was removed like 6 years ago, but then factored out into its own module that brew just knows to install when you want to use it.

But it also isn't working on Travis today: see https://github.com/Homebrew/homebrew-bundle/issues/646

**Comment by adamnovak** [comment]
I've made https://github.com/vgteam/vg/pull/2652 to try and fix this. If that works it can be merged into this branch.

**Comment by adamnovak** [comment]
Upgrading Homebrew makes it upgrade Protobuf, which means we have to clear the caches because our build system can't detect the dependency on the Protobuf version.

**Comment by adamnovak** [comment]
OK @jeizenga, rebase/merge master into this and clear the branch/PR caches and it should work.

**Pull request merged**
