### PR TITLE
Support building with Apple Clang on Mac

### LINKED ISSUE #1246: clang now supports openmp
https://clang-omp.github.io/

We might consider fully supporting our build using it.

### PR DESCRIPTION
**Pull request by adamnovak**
This PR depends on:
- [X] https://github.com/vgteam/vcflib/pull/11
- [x] https://github.com/edawson/gfakluge/pull/41
- [x] https://github.com/benedictpaten/sonLib/pull/34
- [X] https://github.com/vgteam/structures/pull/6
- [X] https://github.com/jltsiren/gcsa2/pull/35
- [X] https://github.com/jltsiren/gbwt/pull/1
- [X] https://github.com/yoheirosen/sublinear-Li-Stephens/pull/4

This PR will fix #1246 and let vg build with the default Clang compiler on Mac. We should no longer need to instruct Mac users to replace their system compiler, or have epic issue threads in which dueling compilers and standard libraries battle each other for control of our users systems.

```
Vyoma:vg anovak$ bin/vg version
vg version v1.10.0-59-ga061f801 "Rionero"
Compiled with Apple LLVM version 9.0.0 (clang-900.0.39.2) on Darwin
Built by anovak@Vyoma
Vyoma:vg anovak$ bin/vg test
warning:[BaseAligner::maximum_mapping_quality_exact]: Max score of 0 is the padding score; changing to -10
warning:[BaseAligner::maximum_mapping_quality_approx]: Max score of 0 is the padding score; changing to -10
index file /var/folders/ws/t7b9wm2j2b7fy4_xyq0n5vh00000gn/T//vg-2mOnPd/vg-iC10dg.fai not found, generating...
index file /var/folders/ws/t7b9wm2j2b7fy4_xyq0n5vh00000gn/T//vg-2mOnPd/vg-DdgmBL.fai not found, generating...
GGCTTGGAAATTTTCTGGAGTG
===============================================================================
All tests passed (282024 assertions in 271 test cases)
```

Still TODO:

- [x] Merge all the above PRs so Jenkins and Travis have a hope of testing this.
- [x] Update the documentation for Macports builds to include installing libomp and not GNU GCC.
- [x] Work out the exact package selection to install via Homebrew to do the same thing.

### CODE REVIEW

**Comment by adamnovak** [comment]
OK, it definitely builds under Clang, but now the tests on Travis fail when using Clang because `vg sim` is producing new and different output under clang for each seed.

I will go through the vg sim RNG code and work out how to make it consistent across compilers.

**Comment by jltsiren** [comment]
It's most likely the same issue we had with the subsampling `locate()` in GCSA2. The C++ standard does not specify the exact algorithms used in random number distributions such as `std::uniform_int_distribution`. Every time we use a distribution from `<random>`, we add a new place where the behavior depends on the standard library implementation.

Another possible issue is iterating over the values in `std::unordered_set` or `std::unordered_map`. We also had that in GCSA2.

**Comment by adamnovak** [comment]
Yeah, it looks like distributions not being properly deterministic and portable is a big part of my problems. I'll see about getting rid of them somehow.

**Comment by adamnovak** [comment]
One of the Jenkins tests failed with an `httplib.BadStatusLine`, and our Toil is still too old to retry on those.

Jenkins, test this please.

**Comment by adamnovak** [comment]
Jenkins is now happy, and I have a PR I want to make on top of this, so I am going to merge without waiting for the real status update.

**Comment by ekg** [comment]
Thank you Adam, this should resolve a huge amount of support pain we had.

**Pull request merged**
