### PR TITLE
Support for clang-omp build

### PR DESCRIPTION
**Pull request by buske**
Explicit template required for casting bit to direct to ostream.

This is a re-PR of https://github.com/vgteam/vg/pull/380 from a branch within VG repo.

### CODE REVIEW

**Comment by adamnovak** [comment]
Can you get Travis to build with clang-omp?

**Comment by buske** [comment]
I have the travis commit ready, but it will break the build until https://github.com/jltsiren/gcsa2/pull/23 is merged. Shall I add that to this PR?

**Comment by buske** [comment]
The previous gcsa2 PR was merged, but changes on master since then break the build, so this PR is blocking on https://github.com/jltsiren/gcsa2/pull/24.

**Comment by ekg** [comment]
Weirdly, it's failing with something like

```
/Users/travis/build/vgteam/vg/src/vg.hpp:18:10: fatal error: 'gcsa.h' file not found
#include "gcsa.h"
```

**Comment by buske** [comment]
Yeah, not sure what's causing that. Also seeing
```
In file included from src/mapper.cpp:2:
In file included from /Users/travis/build/vgteam/vg/src/mapper.hpp:10:
/Users/travis/build/vgteam/vg/src/index.hpp:9:10: fatal error: 'rocksdb/db.h' file not found
#include "rocksdb/db.h"
         ^
1 error generated.
make: *** [obj/mapper.o] Error 1
```

The build succeeds on my system but I haven't tried a completely fresh install. Could be caused by parallelizing `make` and some underspecified targets. Will look into it. :)

**Comment by adamnovak** [comment]
Could be a cache problem; all the include files are copied over to the
cache, and the Makefile probably isn't smart enough to know when they need
to be updated. I will clear out the Travis cache.

**Comment by adamnovak** [comment]
Actually, that makes no sense as caches are per-compiler. I already cleared
the caches; maybe it will help anyway.

**Comment by adamnovak** [comment]
OK, it now builds on Travis, but many of the tests fail.

**Comment by buske** [comment]
Based on the travis logs, it still looks like it's failing due to missing header files, no? I'm going through the makefile and adding unstated dependencies now. I believe this should make the caching more robust.

**Comment by adamnovak** [comment]
It looks like "clang-omp" is no longer a Homebrew package, and normal LLVM handles it.

**Comment by ekg** [comment]
I wonder if it's time to explore this again. clang builds would be great!

**Comment by ekg** [comment]
This is still interesting to me. Should we reinitiate? It may be easier than starting from this branch. Sorry @buske

**Comment by buske** [comment]
No worries! :)

**Pull request closed without merging**
