### PR TITLE
Improve bam

### LINKED ISSUE #369: vg surject loses pairing information
Would be super handy to preserve this (and our eventual mapping qualities), to be able to see how other callers perform on vg alignments.

### PR DESCRIPTION
**Pull request by adamnovak**
This should fix #369 and will make some headway on #1424.

Now we crossreference paired reads in surjected GAM to BAM when `-i` is passed, and we leave their /1 and /2 on. We don't flag them paired  or rename them when `-i` isn't passed.

I also moved where the URL encoding is happening to just SAM that goes into URLs, and moved the old surject `-i`, for a file of paths, to `-F`.

Also, I stopped using uninitialized memory for read positions for unmapped reads.

### CODE REVIEW

**Comment by adamnovak** [comment]
We probably still want to look at how the direct output to SAM?BAM works. I made separate paired/unpaired Alignment conversion functions, and the existing code might call the paired functions (which match the old signatures) always.

**Comment by ekg** [comment]
I would *really* love to use SeqLib to manage the htslib format IO.

**Comment by ekg** [comment]
I moved to start merging through this conflict, but I'm worried that this doesn't also fix the problems in map_main, which is also capable of producing cram/bam/sam output. Could we talk about what needs to change, or if it's easier would you please match master and fix the mapper output in the same way as well?

**Comment by adamnovak** [comment]
I've just fixed up map to care about whether the reads are paired or unpaired when surjecting. Now I'm going to rebase on master and fix up the conflicts.

**Comment by adamnovak** [comment]
OK, master is now merged into this branch, and I fixed whai I was complaining about at https://github.com/vgteam/vg/pull/1427#issuecomment-364539524

**Pull request merged**
