### PR TITLE
Sv sanity - GAM index recall

### PR DESCRIPTION
**Pull request by edawson**
Fixes some bugs that prevented GAM index-based variant recall from working. Requires alignments supporting a variant to be anchored on a reference node.

### CODE REVIEW

**Comment by adamnovak** [comment]
Jenkins is very upset about something to do with htslib here:

```
[91mIn file included from ./cram/cram.h:48:0,
                 from cram/cram_encode.c:43:
cram/cram_encode.c: In function 'add_read_names':
[0m[91mcram/cram_encode.c:1238:45: error: 'bam1_core_t {aka struct <anonymous>}' has no member named 'l_extranul'
      BLOCK_APPEND(s->name_blk, bam_name(b), bam_name_len(b));
                                             ^
[0m[91mcram/cram_encode.c:1238:45: error: 'bam1_core_t {aka struct <anonymous>}' has no member named 'l_extranul'
      BLOCK_APPEND(s->name_blk, bam_name(b), bam_name_len(b));
                                             ^
[0m[91mcram/cram_encode.c:1238:45: error: 'bam1_core_t {aka struct <anonymous>}' has no member named 'l_extranul'
      BLOCK_APPEND(s->name_blk, bam_name(b), bam_name_len(b));
                                             ^
[0m[91mIn file included from ./cram/cram.h:45:0,
                 from cram/cram_encode.c:43:
cram/cram_encode.c:1239:24: error: 'bam1_core_t {aka struct <anonymous>}' has no member named 'l_extranul'
      cr->name_len    = bam_name_len(b);
                        ^
[0m[91mcram/cram_encode.c: In function 'process_one_read':
[0m[91mcram/cram_encode.c:2886:57: error: 'bam1_core_t {aka struct <anonymous>}' has no member named 'l_extranul'
      char *key = string_ndup(s->pair_keys, bam_name(b), bam_name_len(b));
                                                         ^
[0mlibtool: compile:  /usr/bin/g++ -DHAVE_CONFIG_H -I. -g -O2 -MT snappy-c.lo -MD -MP -MF .deps/snappy-c.Tpo -c snappy-c.cc  -fPIC -DPIC -o .libs/snappy-c.o
Makefile:134: recipe for target 'cram/cram_encode.o' failed
[91mmake[4]: *** [cram/cram_encode.o] Error 1
[0mmake[4]: Leaving directory '/vg/deps/vcflib/tabixpp/htslib'
Makefile:38: recipe for target 'htslib/libhts.a' failed
[91mmake[3]: *** [htslib/libhts.a] Error 2
```

**Comment by edawson** [comment]
May have to do with an existing issue on vcflib; some changes to the vcflib/tabixpp makefile that lost the `-llzma` in the lib flags. Very odd that Travis is not affected.

**Comment by adamnovak** [comment]
Travis does some "clever" caching that might be masking the problem. It may be that the vg makefile rules don't actually attempt to rebuild vcflib (or one of the other dependencies between vg and the problem) given the updates that have been made.

**Comment by edawson** [comment]
I totally forgot about caching. I bet that's it.

Thanks for tracking this down.

**Comment by edawson** [comment]
This is a manifestation of https://github.com/samtools/htslib/issues/347. I had to update our deps/htslib to the same version as that used by tabixpp/htslib. Travis caches deps, so it wouldn't affect Travis builds.

Thanks Jenkins.

**Pull request merged**
