### PR TITLE
Fix worse mapping

### PR DESCRIPTION
**Pull request by adamnovak**
I found a read that was mapping worse to snp1kg than to primary in the BRCA1 Jenkins test, running locally on kolossus.

This was because the read had a MEM stareting at the beginning of the read and the end of a node (it aligned on the reverse strand), and the cluster subgraph extractor was not looking before that MEM to find any more graph material. The optimal alignment didn't actually use that MEM but instead went a bit further out and matched more repeat units for a better score.

I turned the problem into a unit test, and solved it by cribbing off @jeizenga's cluster graph extractor.

We should pay close attention to how many CI warnings about misbehaving reads Jenkins throws. I want them to come down from 72 (on Jenkins) for BRCA1 and 390 (on Jenkins) for MHC.

Oddly, I get different sets of warnings when I run the Jenkins tests locally versus on Jenkins. I think `toil-vg` is generating different reads with `vg sim`. Maybe @cmarkello knows if there's a difference in how the reads are seeded somehow.

This is related to #881 and may fix it if it's good enough.

### CODE REVIEW

**Comment by jeizenga** [comment]
Aside: while I was showing this to you I found a mistake with how I calculated the distance bounds. The code is corrected on my branch here:

https://github.com/jeizenga/vg/blob/multipath-alignments/src/multipath_mapper.cpp#L137

**Comment by adamnovak** [comment]
Looks like this is going to take some more work, since it lowers performance the way I have it now, especially remapping against the input graph. Even with the corrected distance bounds, this might be a case of more-principled-but-worse.

**Comment by adamnovak** [comment]
This is reducing the number of reads which disobey our score invariants.

The Mac Travis test is failing because @mlin cleared the cache, and the build is taking too long (and getting killed by Travis) because it's trying to rebuild its empty cache. Our OSX builds are likely to fail forever unless we reduce the amount of code being compiled or adopt a clever partial-build solution to fill up the cache. I'm going to merge this PR anyway.

The other concern here is, because of the way I am now doing graph extraction and alignment deduplication, we can get low mapping qualities when two different alignments to the same local region are generated. We will probably want to add a bit of context expansion to the graph extraction, and/or port over the idea of merging overlapping clusters from the multipath mapper.

**Comment by adamnovak** [comment]
@jeizenga @glennhickey It looks like this PR is the one that messed up paired end mapping. The AUC for snp1kg-pe went from ~0.80 to ~0.65, and we didn't get a test failure.

**Pull request merged**
