### PR TITLE
Yes, it's really important to be correct

### PR DESCRIPTION
**Pull request by ekg**
Here I'm investigating why we have such poor allele balance at hets that aren't in the graph, much worse than bwa mem.

### CODE REVIEW

**Comment by ekg** [comment]
@jeizenga do you have a commit that's not far from master where this mpmap test doesn't fail?

**Comment by jeizenga** [comment]
I think the furthest along commit I have that isn't showing this failure is here (but it does have some other failure in map):
https://github.com/vgteam/vg/pull/1222

**Comment by ekg** [comment]
Uh am I misreading this or did the jobs fail because they couldn't find ggrepel??? Weird!??! I'll do a local test.

**Comment by ekg** [comment]
I'm closing this branch as I don't see any improvement over master.

**Pull request closed without merging**
