### PR TITLE
Merging refactoring of genotypekit

### PR DESCRIPTION
**Pull request by jeizenga**
I also have some other updates in here that aren't separated into any branch, so I guess we'll have to merge those too. I don't think they'll conflict with anything.

For genotype/genotypekit:
- Created refactored TraversalFinder and SiteFinder objects
- Discontinued support for supbub
- Added more explicit documentation for the genotypekit interfaces

Other changes:
- Multipath alignments added
- Phased genome object added
- Possibly some of Erik's edits to map-good

### CODE REVIEW

**Comment by jeizenga** [comment]
@glennhickey 
The CI that's running right now is going to fail, but I'm pretty sure at this point that the only thing holding it up is the msga tests that were also failing in Mapperific. I guess some of the map-good changes must have made it into my fork's master (I'll be better about branches from now on, promise). Anyway, Erik says he has a fix for it, so I think the best option is just to wait for him to get the build right and merge mapperific into master. Then we can sync up here and get on with things.

I gather that you're working on other things right now anyway, which is fine since we're going to have to wait for that merge. In the meantime, I'm going to keep moving forward with the refactor.

**Comment by glennhickey** [comment]
Sounds good to me.  Yeah, I have at least another couple days of full time
toil-ing so by all means don't let me hold you back.

**Comment by adamnovak** [comment]
Should I merge this in?

Is there a reason it touches 81 files? What has actually changed?

**Comment by jeizenga** [comment]
Most of that is a merge with master. The branch I was developing on got dirtied up with a partially complete map-good that didn't pass Travis, so I merged master in so now that Erik has it working. Now Travis is happy.

Prolly only 10ish files actually got new changes here. The main ones I want in this branch are some modifications to the genotypekit documentation/APIs, refactored versions of genotyper functions into genotypekit objects, snarl sites, and snarlmanagers. Some other things that found their way into this PR (because I was bad at branching) are the multipath alignments, the phased genome object, and some revamped documentation.

Anyway, I'm pretty sure git is smart enough to figure out which commits are duplicates from master when we merge this branch back in, right? Is there any compelling reason not to merge?

**Comment by adamnovak** [comment]
If Erik rebased his commits after you pulled them in, then we'll have
duplicate copies of them in the history. But we hardly ever use the history
in ways that would make that a problem, and clearly Git isn't having merge
conflicts.

**Comment by ekg** [comment]
@jeizenga this PR was epic

**Comment by glennhickey** [comment]
It's still in its own branch and not in master btw.

**Comment by glennhickey** [comment]
@jeizenga github's giving me grief about a bunch of conflicts when trying
to PR against master.  Think you will need to rebase locally (can use -i to
squash some commits while at it) then re-PR.. Or perhaps someone more
git-savvy can fix.

**Pull request merged**
