### PR TITLE
Giraffe Facts

### PR DESCRIPTION
**Pull request by adamnovak**
I've written a "Giraffe Facts" script that can analyze the output GAMs from `vg gaffe` and produce summary statistics about where time is going.

You use it like this:

```
vg view -aj trash/clustering/mapped.gam | scripts/giraffe-facts.py trash/clustering/outdir
┌───────────────────────────────┐
│         Giraffe Facts         │
├───────────────────────────────┤
│Reads                    200000│
├─────────┬────────────────┬────┤
│  Stage  │Reads per Second│Time│
│         │  (cumulative)  │(%) │
├─────────┼────────────────┼────┤
│minimizer│        26871.79│  1%│
│   seed  │         2026.63│  8%│
│ cluster │          532.04│ 24%│
│  extend │          378.46│ 13%│
│  align  │          176.96│ 53%│
│  winner │          176.28│  0%│
├─────────┼────────────────┼────┤
│ Overall │          175.20│100%│
└─────────┴────────────────┴────┘
```

In the specified output directory, it also makes plots of runtime expended up to each stage, per read.

image

I'm somewhat hackily shipping a python 3-ified version of my `histogram.py` script to enable this.

### CODE REVIEW

**Comment by jltsiren** [comment]
The seed stage seems surprisingly slow. On my laptop, I get 80,000 to 90,000 reads/second for finding minimizers and collecting the occurrences of all minimizers with at most 10 hits. Maybe the real cost is determining which seeds are close enough to the true alignment, as that involves an `xg_index->nearest_offsets_in_paths()` call for each seed.

**Comment by jeizenga** [comment]
Bonus points to this PR if giraffe-facts.py also tells you a fun fact about giraffes

**Comment by adamnovak** [comment]
@jltsiren It definitely could be that the correctness annotation step is slowing it down. I have it accounted in a substage, but here we're just looking at the top-level stages. Another thing on my to do list is comparing overall speed with and without all my extra instrumentation.

**Comment by adamnovak** [comment]
OK, here's a run with all the tracking on:

```
┌───────────────────────────────┐
│         Giraffe Facts         │
├───────────────────────────────┤
│Reads                    200000│
├─────────┬────────────────┬────┤
│  Stage  │Reads per Second│Time│
│         │  (cumulative)  │(%) │
├─────────┼────────────────┼────┤
│minimizer│        22637.95│  1%│
│   seed  │         2015.13│  7%│
│ cluster │          480.07│ 23%│
│  extend │          330.98│ 14%│
│  align  │          146.52│ 55%│
│  winner │          145.94│  0%│
├─────────┼────────────────┼────┤
│ Overall │          145.03│100%│
└─────────┴────────────────┴────┘
```

And here's a later run with correctness tracking compiled out (so no extra XG queries):

```
┌───────────────────────────────┐
│         Giraffe Facts         │
├───────────────────────────────┤
│Reads                    200000│
├─────────┬────────────────┬────┤
│  Stage  │Reads per Second│Time│
│         │  (cumulative)  │(%) │
├─────────┼────────────────┼────┤
│minimizer│        21071.98│  1%│
│   seed  │         3024.54│  4%│
│ cluster │          508.46│ 24%│
│  extend │          342.57│ 14%│
│  align  │          148.32│ 56%│
│  winner │          147.77│  0%│
├─────────┼────────────────┼────┤
│ Overall │          146.80│100%│
└─────────┴────────────────┴────┘
```

And here it is with only the stage/substage timing and no correctness or provenance tracking:

```
┌───────────────────────────────┐
│         Giraffe Facts         │
├───────────────────────────────┤
│Reads                    200000│
├─────────┬────────────────┬────┤
│  Stage  │Reads per Second│Time│
│         │  (cumulative)  │(%) │
├─────────┼────────────────┼────┤
│minimizer│        19494.50│  1%│
│   seed  │         3307.08│  3%│
│ cluster │          453.08│ 24%│
│  extend │          306.85│ 14%│
│  align  │          129.93│ 57%│
│  winner │          129.42│  0%│
├─────────┼────────────────┼────┤
│ Overall │          128.63│100%│
└─────────┴────────────────┴────┘
```

Overall it's coming out *slower* with the extra tracking code disabled, which I suspect is due to Courtyard load changing between runs; I could spin up a dedicated machine if we want serious numbers. But looking at the percentages, the "seed" stage where I'm computing correctness drops from 7% of runtime to 3-4%, so it looks like I'm slowing it down by a factor of ~2 with the correctness estimation. I also don't see strong evidence that tracking the provenance is taking a long time.

**Comment by benedictpaten** [comment]
Hmm.. super helpful. Jouni, do you want to jump in here and figure what's going on? I would expect much better numbers out of the seed stage, unless courtyard is just insanely slow.

**Comment by adamnovak** [comment]
I did some interleaved comparison runs between just per-read timings, and per-stage timings. I got, overall, 137.99 reads per second just timing the reads, and 137.48 reads per second timing the stages. So timing stages and substages does not have a big impact. I will leave that on by default, and let the correctness and provenance tracking be something you can compile in.

**Comment by jltsiren** [comment]
I ran the same benchmark on an i3.8xlarge instance.

Original:

```
┌───────────────────────────────┐
│         Giraffe Facts         │
├───────────────────────────────┤
│Reads                    200000│
├─────────┬────────────────┬────┤
│  Stage  │Reads per Second│Time│
│         │  (cumulative)  │(%) │
├─────────┼────────────────┼────┤
│minimizer│       151942.67│  1%│
│   seed  │         6326.24│ 12%│
│ cluster │         2470.70│ 19%│
│  extend │         1837.92│ 11%│
│  align  │          785.08│ 57%│
│  winner │          782.75│  0%│
├─────────┼────────────────┼────┤
│ Overall │          779.17│100%│
└─────────┴────────────────┴────┘
```

Without correctness checking for the seeds:

```
┌───────────────────────────────┐
│         Giraffe Facts         │
├───────────────────────────────┤
│Reads                    200000│
├─────────┬────────────────┬────┤
│  Stage  │Reads per Second│Time│
│         │  (cumulative)  │(%) │
├─────────┼────────────────┼────┤
│minimizer│       149448.49│  1%│
│   seed  │        20508.52│  3%│
│ cluster │         3296.91│ 21%│
│  extend │         2227.36│ 12%│
│  align  │          837.80│ 62%│
│  winner │          834.77│  0%│
├─────────┼────────────────┼────┤
│ Overall │          830.33│100%│
└─────────┴────────────────┴────┘
```

Without correctness checking for the seeds and any `funnel.processing_input()` / `funnel.processed_input()` calls:

```
┌───────────────────────────────┐
│         Giraffe Facts         │
├───────────────────────────────┤
│Reads                    200000│
├─────────┬────────────────┬────┤
│  Stage  │Reads per Second│Time│
│         │  (cumulative)  │(%) │
├─────────┼────────────────┼────┤
│minimizer│       150845.25│  1%│
│   seed  │        42105.05│  1%│
│ cluster │         3639.93│ 22%│
│  extend │         2407.04│ 12%│
│  align  │          867.26│ 63%│
│  winner │          864.08│  0%│
├─────────┼────────────────┼────┤
│ Overall │          859.43│100%│
└─────────┴────────────────┴────┘
```

**Comment by jltsiren** [comment]
And the new version without `TRACK_PROVENANCE` and `TRACK_CORRECTNESS`:

```
┌───────────────────────────────┐
│         Giraffe Facts         │
├───────────────────────────────┤
│Reads                    200000│
├─────────┬────────────────┬────┤
│  Stage  │Reads per Second│Time│
│         │  (cumulative)  │(%) │
├─────────┼────────────────┼────┤
│minimizer│       182549.49│  0%│
│   seed  │        62907.49│  1%│
│ cluster │         3928.52│ 22%│
│  extend │         2610.56│ 12%│
│  align  │          909.48│ 65%│
│  winner │          906.73│  0%│
├─────────┼────────────────┼────┤
│ Overall │          902.14│100%│
└─────────┴────────────────┴────┘
```

**Comment by benedictpaten** [comment]
Hi Jouni, is this multi threaded or single core performance? Prefer single
core numbers for now.

**Comment by jltsiren** [comment]
These are all single-core results.

**Comment by benedictpaten** [comment]
That's exciting! What are the comparable Bwa mem and minimap numbers on
this system? Also, does this use Xian's latest?

**Comment by jltsiren** [comment]
BWA-MEM speed is ~8,000 reads/second, while minimap2 speed is ~15,000 reads/second. Both times are as reported by the tools themselves for single-threaded runs.

**Comment by benedictpaten** [comment]
Thanks for that Jordan! @adamnovak @xchang1 Does this include Xian's newest, fastest clusterer. It would seem from Jouni's numbers that doubling the speed of the clusterer would get us quite close to having the seed/cluster/extend stages fast enough, particularly as we are currently extending all clusters? and there is therefore room to discard likely non-productive clusters at that stage.

**Comment by adamnovak** [comment]
Xian's latest clusterer is in #2218, and not merged into this yet.

We should merge both these PRs and then look at the speed results.

**Pull request merged**
