### PR TITLE
Error in tutorial fixed

### PR DESCRIPTION
**Pull request by colindaven**
-d in vg surject was not found. 

Changed to minimal required options

### CODE REVIEW

**Comment by jeizenga** [comment]
@ekg is this something you touched with your work on surject?

**Comment by adamnovak** [comment]
Jenkins, test this please.

**Comment by adamnovak** [comment]
OK to test.

**Comment by adamnovak** [comment]
Jenkins just doesn't give me the respect I deserve.

Since this is a documentation change I am going to forgo the Jenkins testing and merge it in.

**Pull request merged**
