### PR TITLE
Revise mpmap testing

### PR DESCRIPTION
**Pull request by adamnovak**
Rather than refactor everything to be public static methods, I'm making all the internal stuff we might want to test protected (instead of private) and defining a class in the tests that exposes it.
I think this makes sense: we need to test the internal API that derived classes might want to use, but in Catch we can't do friend declarations, so this is the next best way.

I'm also adding a couple of new tests that make sure topologically_ordered_subpaths isn't incredibly broken.

### CODE REVIEW

**Comment by adamnovak** [comment]
`E   AssertionError: 0.981275507129 not greater than or equal to 0.981689777152`

This looks like nondeterminism to me.

Jenkins test this please.

**Comment by adamnovak** [comment]
A bunch of little tests on Jenkins that I didn't touch are failing here, so I'm stopping the test.

**Comment by glennhickey** [comment]
It's even happening to toil-vg
http://jenkins.cgcloud.info/job/toil-vg/604/console

**Comment by adamnovak** [comment]
Jenkins, test this please.

**Comment by adamnovak** [comment]
OK, Jenkins has been fixed, and the failure here looks mostly like AUC nondeterminism; we see the same thing on master.

**Pull request merged**
