### PR TITLE
Make cactus bubbles more robust to dangling nodes

### PR DESCRIPTION
**Pull request by glennhickey**
Dangling nodes can cause cactus bubbles to be wrong, or crash (#396).  Try to fix this by choosing better source and sink (Still testing)

### CODE REVIEW

**Comment by adamnovak** [comment]
Is there a real difference between `vg mod -a` and `vg stats -C`?

**Comment by glennhickey** [comment]
mod -a returns the topology of the cactus graph (viewable in graphviz).
This is handy to help debug cactus-related stuff, and generally not super
obvious by looking at the ID sets of bubbles returned by stats -C.

**Comment by glennhickey** [comment]
Current version should fix crash but is bandaid solution.  As discussed, source and sink should get picked up from the original (non-augmented graph).  Furthermore, the dangling nodes don't really help call anything, so they should get ignored by bubble construction (ideally removed entirely).

**Comment by ekg** [comment]
Don't we want to work from the augmented graph? From there we can always
find our way back to the original graph.

**Comment by glennhickey** [comment]
Yeah, the idea was just to use the translator to find the augmented source
and sink with the help of the original graph (where there's less ambiguity
in this department).  Still not sure if this is better than just using the
reference path (as done currently)

**Pull request merged**
